import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createRecoveryFixture} from './pg-fixture.js';
import {census,freePort,launchOwned,stopOwned,waitUntil,type OwnedChild} from './process-fixture.js';
import {migrateRecovery} from '../src/migration.js';
import {migrateNativeHistory} from '../src/native-migration.js';
import {migrateEffectHistory} from '../src/effect-migration.js';
import {migrateFences} from '../src/fence-migration.js';
import {migrateDispatch} from '../src/dispatch-migration.js';
import {migrateResults} from '../src/result-migration.js';
import {audienceDigest,type AudienceRow} from '../../g1-identity/src/audience.js';
import {bindingDigest,runSchema} from '../src/contracts.js';
import {AuthenticatedUnitOfWork} from '../../g1-identity/src/authenticated-uow.js';
import {PostgresUnitOfWork} from '../../g1-foundations/src/postgres-uow.js';
import {RecoveryRepository} from '../src/repository.js';
import {ResultRepository,type Outcome} from '../src/result-repository.js';
import {NotificationRepository,notificationHint,notificationHintSchema,type NotificationRecord} from '../src/notification-repository.js';
let f:Awaited<ReturnType<typeof createRecoveryFixture>>,directory:string,journal:string,port:number,endpoint:string,external:OwnedChild,results:ResultRepository,notifications:NotificationRepository;
const owner=randomUUID(),children:OwnedChild[]=[];
before(async()=>{
 census();f=await createRecoveryFixture();
 await migrateRecovery(f.admin,{ownedSyntheticDatabase:true,sqlPath:resolve('migrations/0004_recovery.sql')});
 await migrateNativeHistory(f.admin,resolve('migrations/0005_native_history.sql'));await migrateEffectHistory(f.admin,resolve('migrations/0006_effect_reconciliation.sql'));await migrateFences(f.admin,resolve('migrations/0007_fences.sql'));await migrateDispatch(f.admin,resolve('migrations/0008_dispatch.sql'));await migrateResults(f.admin,resolve('migrations/0009_results.sql'));
 results=new ResultRepository(f.repo);notifications=new NotificationRepository(f.repo);
 directory=await mkdtemp(resolve(tmpdir(),'fabric-notifications-'+owner+'-'));await writeFile(resolve(directory,'owner'),owner,{flag:'wx'});journal=resolve(directory,'notifications.jsonl');port=await freePort();endpoint='http://127.0.0.1:'+port;await startExternal();
});
after(async()=>{const errors:unknown[]=[];for(const child of children.toReversed())try{await stopOwned(child);}catch(e){errors.push(e);}try{if(journal){const journalText=await readFile(journal,'utf8');console.log(JSON.stringify({measurement:'notification-raw-journal',owner,journalText,journalBytes:Buffer.byteLength(journalText),journalSha256:createHash('sha256').update(journalText).digest('hex'),services:children.filter(c=>c.output().includes('databaseCredentials')).map(c=>({pid:c.pid,stdout:c.output(),stderr:c.errors()}))}));}}catch(e){errors.push(e);}try{await f?.close();}catch(e){errors.push(e);}try{if(directory){assert.equal(await readFile(resolve(directory,'owner'),'utf8'),owner);await rm(directory,{recursive:true});console.log(JSON.stringify({measurement:'owned-notification-files-cleanup',owner,removed:true}));}}catch(e){errors.push(e);}if(errors.length)throw new AggregateError(errors,'Mandatory notification cleanup');});
async function startExternal(){const marker='--fixture-owner='+owner;external=launchOwned(process.execPath,[fileURLToPath(new URL('../src/notification-service-process.js',import.meta.url)),marker],marker,{FABRIC_NOTIFICATION_SERVICE:JSON.stringify({owner,journal,port})});children.push(external);await waitUntil(async()=>{if(external.child.exitCode!==null)throw new Error(external.errors());return external.output().includes('"kind":"ready"');},'independent notification service ready');assert.equal(JSON.parse(external.output().trim().split('\n')[0]!).databaseCredentials,false);console.log(JSON.stringify({measurement:'independent-notification-service',owner,pid:external.pid,hasControllerCredentials:false}));}
async function mode(ack='normal',lookup='normal'){assert.equal((await fetch(endpoint+'/fixture-mode',{method:'POST',body:JSON.stringify({ack,lookup})})).status,200);}
async function metrics(){return await (await fetch(endpoint+'/metrics')).json() as {posts:number;writes:number;lookups:number;hints:Record<string,unknown>[]};}
async function seed(status:Outcome['status']='succeeded',lostCommit=false){
 const scope=await f.scopeFor(1),s=await f.seedRun(scope);await f.repo.initialize(scope,s.init,s.value);
 const rows=await f.uow.withScope(await f.scopeFor(0),async tx=>(await tx.query('SELECT fabric.identity_audience($1,$2,$3) AS audience',[f.source,f.space,f.sourceTask])).rows[0]?.audience as AudienceRow[]),audience={sourceSpaceId:f.source,sourceTaskId:f.sourceTask,destinationSpaceId:f.space,recipientActorIds:rows.map(r=>r.actorId),revisionDigest:audienceDigest(rows)};
 await results.configure(scope,s.runId,{obligation:'draft',definitions:[{kind:'contains',argument:'agreed'}],audience});
 const artifactId=randomUUID();await results.saveDraft(scope,s.runId,1,artifactId,1,null,'agreed secret draft '+s.runId);await results.verify(scope,s.runId,1,artifactId,1);
 let r=s.value.run;for(const state of status==='cancelled'?['running','cancelling'] as const:status==='failed'?['running'] as const:['running','verifying'] as const){const run=runSchema.parse({...r,revision:r.revision+1,state}),cp={run,session:s.value.session,result:null};await f.repo.checkpoint(scope,f.mutation(s.runId,r.revision,cp),cp);r=run;}
 const input={status,summary:'sensitive result '+s.runId,artifactId,version:1,deliveryId:null,remainingWork:status==='succeeded'?'none':'needs review'};
 let outcome:Outcome;if(lostCommit){const lost=new ResultRepository(new RecoveryRepository(new AuthenticatedUnitOfWork({foundation:new PostgresUnitOfWork(f.controller,()=>{throw new Error('Lost result/outbox commit ACK');}),bindingFor:f.bindingFor}),f.bindingFor));await assert.rejects(lost.finish(scope,s.runId,1,input),e=>(e as {code?:string}).code==='UNKNOWN_COMMIT');outcome=(await results.get(await f.scopeFor(1),s.runId)).outcome!;}else outcome=await results.finish(scope,s.runId,1,input);
 const notification=await notifications.enqueue(await f.scopeFor(1),s.runId,f.actors[1]);return {...s,artifactId,outcome,notification};
}
async function fresh(action:'get'|'send'|'reconcile'|'notification',s:{runId:string;notification?:NotificationRecord},overrides:Record<string,unknown>={}){const marker='--fixture-owner='+owner,child=launchOwned(process.execPath,[fileURLToPath(new URL('../src/result-worker-process.js',import.meta.url)),marker],marker,{...process.env,FABRIC_RESULT_WORKER:JSON.stringify({owner,dsn:f.dsn,issuer:f.endpoints.issuer,jwksUrl:f.endpoints.jwksUrl,token:f.tokens[1],tenantId:f.tenant,spaceId:f.space,runId:s.runId,action,notificationId:s.notification?.notificationId,endpoint,...overrides})});children.push(child);await waitUntil(async()=>child.child.exitCode!==null||child.child.signalCode!==null,'fresh result broker exit',10000);const records=child.output().trim().split('\n').map(line=>JSON.parse(line) as Record<string,unknown>);assert.equal(records[0]?.sessionCacheEntries,0);assert.equal(records.at(-1)?.closed,true);assert.equal(census().some(r=>r.pid===child.pid),false);console.log(JSON.stringify({measurement:'fresh-result-broker',owner,pid:child.pid,action,exitCode:child.child.exitCode,removed:true,modelCalls:0}));return {child,records,result:records.find(r=>r.kind==='result')?.result as any};}

test('1 real rejecting adapter keeps checked draft Task success and fresh result retrieval',async()=>{const s=await seed();await mode('reject');const before=await metrics();const n=await notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint);assert.equal(n.state,'failed');assert.equal(n.attempts,1);assert.equal((await metrics()).writes,before.writes);const recovered=await fresh('get',s);assert.equal(recovered.child.child.exitCode,0);assert.equal(recovered.result.outcome.resultDigest,s.outcome.resultDigest);assert.equal(recovered.result.outcome.status,'succeeded');assert.equal(recovered.result.artifacts[0].bytes,'agreed secret draft '+s.runId);assert.deepEqual(recovered.result.deliveries,[]);assert.equal((await fresh('notification',s)).result.state,'failed');});
test('2 deduplicated enqueue is stable under concurrent current controller commands',async()=>{const s=await seed();const all=await Promise.all(Array.from({length:10},async()=>notifications.enqueue(await f.scopeFor(1),s.runId,f.actors[1])));assert.ok(all.every(n=>n.notificationId===s.notification.notificationId));assert.equal((await f.admin.query("SELECT count(*) AS count FROM fabric.recovery_notifications WHERE tenant_id=$1 AND run_id=$2 AND record->>'recipientId'=$3",[f.tenant,s.runId,f.actors[1]])).rows[0].count,'1');assert.equal((await f.admin.query('SELECT count(*) AS count FROM fabric.recovery_notifications WHERE tenant_id=$1 AND run_id=$2',[f.tenant,s.runId])).rows[0].count,'3');});
test('3 bounded rejection retry is durable across three actual broker processes',async()=>{const s=await seed();await mode('reject');const before=await metrics();for(let i=1;i<=3;i++){const r=await fresh('send',s);assert.equal(r.result.state,'failed');assert.equal(r.result.attempts,i);}const exhausted=await fresh('send',s);assert.equal(exhausted.result.attempts,3);assert.equal(exhausted.result.nextAction,'retry-bound-exhausted');assert.equal((await metrics()).posts-before.posts,3);assert.equal((await fresh('get',s)).result.outcome.status,'succeeded');});
test('4 rejection followed by acknowledged success keeps original dedup identifier',async()=>{const s=await seed();await mode('reject');await notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint);await mode();const n=await notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint);assert.equal(n.notificationId,s.notification.notificationId);assert.equal(n.state,'sent');assert.equal(n.attempts,2);assert.equal((await results.get(await f.scopeFor(1),s.runId)).outcome?.status,'succeeded');});
test('5 lost acknowledgement remains unknown and recreating adapter/controller reconciles GET with zero replay POST',async()=>{const s=await seed();await mode('drop');const before=await metrics();const n=await notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint);assert.equal(n.state,'unknown');const committed=await metrics();assert.equal(committed.posts-before.posts,1);assert.equal(committed.writes-before.writes,1);await stopOwned(external);await startExternal();const after=await metrics();const recovered=await fresh('reconcile',s);assert.equal(recovered.result.state,'sent');const last=await metrics();assert.equal(last.posts,after.posts);assert.equal(last.writes,after.writes);assert.equal(last.lookups-after.lookups,1);assert.equal((await fresh('get',s)).result.outcome.resultDigest,s.outcome.resultDigest);});
test('6 unknown send repeated by recreated worker cannot replay POST',async()=>{const s=await seed();await mode('drop');await notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint);const before=await metrics();const r=await fresh('send',s);assert.equal(r.result.state,'unknown');assert.equal((await metrics()).posts,before.posts);assert.equal(r.result.nextAction,'lookup-original-id-no-retry');});
for(const lookup of ['unsupported','absent','outage','mismatch'])test('7 '+lookup+' lookup remains unknown without publication retry',async()=>{const s=await seed();await mode('drop',lookup);await notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint);const before=await metrics();const n=await notifications.reconcile(await f.scopeFor(1),s.notification.notificationId,endpoint);assert.equal(n.state,'unknown');assert.equal(n.attempts,1);assert.equal((await metrics()).posts,before.posts);await mode();assert.equal((await notifications.reconcile(await f.scopeFor(1),s.notification.notificationId,endpoint)).state,'sent');});
test('8 crash after fsynced delivery loses worker cache but preserves uncertain marker and GET reconciliation',async()=>{const s=await seed();await mode('hold');const before=await metrics(),marker='--fixture-owner='+owner;const child=launchOwned(process.execPath,[fileURLToPath(new URL('../src/result-worker-process.js',import.meta.url)),marker],marker,{...process.env,FABRIC_RESULT_WORKER:JSON.stringify({owner,dsn:f.dsn,issuer:f.endpoints.issuer,jwksUrl:f.endpoints.jwksUrl,token:f.tokens[1],tenantId:f.tenant,spaceId:f.space,runId:s.runId,action:'send',notificationId:s.notification.notificationId,endpoint})});children.push(child);await waitUntil(async()=>(await metrics()).writes>before.writes,'fsynced notification crash barrier');await stopOwned(child,'SIGKILL');assert.equal((await notifications.get(await f.scopeFor(1),s.notification.notificationId)).state,'unknown');await stopOwned(external);await startExternal();const current=await metrics();assert.equal((await fresh('reconcile',s)).result.state,'sent');assert.equal((await metrics()).posts,current.posts);assert.equal((await fresh('get',s)).result.outcome.resultDigest,s.outcome.resultDigest);});
test('9 concurrent notification senders produce one durable external hint',async()=>{const s=await seed();await mode();const before=await metrics();const all=await Promise.all(Array.from({length:10},async()=>notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint)));assert.ok(all.every(n=>['unknown','sent'].includes(n.state)));assert.equal((await metrics()).posts-before.posts,1);assert.equal((await metrics()).writes-before.writes,1);assert.equal((await notifications.get(await f.scopeFor(1),s.notification.notificationId)).state,'sent');});
for(const status of ['partial','failed','cancelled'] as const)test('10 sent notification never hides '+status+' Task evidence after fresh recovery',async()=>{const s=await seed(status);await mode();const n=await notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint);assert.equal(n.state,'sent');const r=await fresh('get',s);assert.equal(r.result.outcome.status,status);assert.equal(r.result.outcome.resultDigest,s.outcome.resultDigest);assert.equal(r.result.outcome.remainingWork,'needs review');assert.equal(r.result.artifacts.length,1);});
test('11 hints contain only identifiers/deep link, never summaries/bytes/credentials or bearer authority',async()=>{const s=await seed();await mode();await notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint);const hint=(await metrics()).hints.find(h=>h.notificationId===s.notification.notificationId)!;assert.deepEqual(hint,notificationHint(s.notification));assert.deepEqual(Object.keys(hint).sort(),['deepLink','notificationId','recipientId','resultDigest','runId']);assert.equal(JSON.stringify(hint).includes('sensitive'),false);assert.equal(JSON.stringify(hint).includes('secret draft'),false);assert.throws(()=>notificationHintSchema.parse({...hint,summary:'leak'}));await assert.rejects(results.get({...f.issued[1]} as typeof f.issued[1],s.runId));});
test('12 notification deep link and original run cannot cross Space',async()=>{const s=await seed();const other=await f.scopeFor(1,f.source);await assert.rejects(results.get(other,s.runId));await assert.rejects(notifications.get(other,s.notification.notificationId));await assert.rejects(notifications.enqueue(other,s.runId,f.actors[1]));await assert.rejects(notifications.send(other,s.notification.notificationId,endpoint));const r=await fresh('get',s,{spaceId:f.source});assert.equal(r.child.child.exitCode,1);assert.equal(r.result,undefined);assert.equal(r.records.find(x=>x.kind==='denied')?.code,'UNAUTHORIZED');});
test('13 task reader cannot enqueue/send as owner or executor',async()=>{const s=await seed();const scope=await f.scopeFor(2);await assert.rejects(notifications.enqueue(scope,s.runId,f.actors[1]));await assert.rejects(notifications.send(scope,s.notification.notificationId,endpoint));assert.equal((await results.get(scope,s.runId)).outcome?.resultDigest,s.outcome.resultDigest);});
test('14 current recipient revocation refuses enqueue/send/lookup and result retrieval with no POST',async()=>{const s=await seed(),before=await metrics();await f.admin.query('UPDATE fabric.memberships SET revoked_at=clock_timestamp(),revision=revision+1 WHERE tenant_id=$1 AND space_id=$2 AND actor_id=$3',[f.tenant,f.space,f.actors[2]]);try{for(const action of [()=>notifications.enqueue(f.issued[1],s.runId,f.actors[2]),()=>notifications.send(f.issued[1],s.notification.notificationId,endpoint),()=>notifications.get(f.issued[1],s.notification.notificationId),()=>results.get(f.issued[1],s.runId)])await assert.rejects(action());assert.equal((await metrics()).posts,before.posts);assert.equal((await fresh('get',s)).child.child.exitCode,1);}finally{await f.admin.query('UPDATE fabric.memberships SET revoked_at=NULL,revision=revision-1 WHERE tenant_id=$1 AND space_id=$2 AND actor_id=$3',[f.tenant,f.space,f.actors[2]]);}});
test('15 revoked current identity session cannot recover by hint while terminal outcome persists',async()=>{const s=await seed(),binding=f.bindingFor(await f.scopeFor(2));await f.admin.query('UPDATE fabric.identity_sessions SET revoked_at=clock_timestamp() WHERE issuer=$1 AND subject=$2 AND sid=$3',[binding.issuer,binding.subject,binding.sessionId]);const r=await fresh('get',s,{token:f.tokens[2]});assert.equal(r.child.child.exitCode,1);assert.equal((await results.get(await f.scopeFor(1),s.runId)).outcome?.resultDigest,s.outcome.resultDigest);});
test('16 wrong endpoint and remote target are rejected before a notification side effect',async()=>{const s=await seed();await mode('drop');await notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint);const before=await metrics();for(const bad of ['https://example.invalid','http://127.0.0.1:1','http://127.0.0.1:2/notifications','http://user:secret@127.0.0.1:2']){await assert.rejects(notifications.send(await f.scopeFor(1),s.notification.notificationId,bad));await assert.rejects(notifications.reconcile(await f.scopeFor(1),s.notification.notificationId,bad));}assert.equal((await metrics()).posts,before.posts);});

test('17 result/outbox commit ACK loss preserves terminal bytes and all pending recipients, exact finish dedup adds zero intents',async()=>{const s=await seed('succeeded',true);const read=await fresh('get',s);assert.equal(read.result.outcome.resultDigest,s.outcome.resultDigest);assert.equal(read.result.outcome.status,'succeeded');const notices=await f.admin.query('SELECT record FROM fabric.recovery_notifications WHERE tenant_id=$1 AND space_id=$2 AND run_id=$3',[f.tenant,f.space,s.runId]);assert.equal(notices.rows.length,3);assert.ok(notices.rows.every(r=>(r.record as NotificationRecord).state==='pending'));const duplicate=await results.finish(await f.scopeFor(1),s.runId,1,{status:'succeeded',summary:s.outcome.summary,artifactId:s.artifactId,version:1,deliveryId:null,remainingWork:'none'});assert.equal(duplicate.resultDigest,s.outcome.resultDigest);assert.equal((await f.admin.query('SELECT count(*) AS count FROM fabric.recovery_notifications WHERE tenant_id=$1 AND run_id=$2',[f.tenant,s.runId])).rows[0].count,'3');});
test('18 notification dispatch marker commit ACK loss causes zero I/O, durable unknown cannot replay after recreation',async()=>{const s=await seed();await mode();const before=await metrics();const lost=new NotificationRepository(new RecoveryRepository(new AuthenticatedUnitOfWork({foundation:new PostgresUnitOfWork(f.controller,()=>{throw new Error('Lost dispatch marker ACK');}),bindingFor:f.bindingFor}),f.bindingFor));await assert.rejects(lost.send(await f.scopeFor(1),s.notification.notificationId,endpoint),e=>(e as {code?:string}).code==='UNKNOWN_COMMIT');assert.equal((await notifications.get(await f.scopeFor(1),s.notification.notificationId)).state,'unknown');assert.equal((await fresh('send',s)).result.state,'unknown');assert.equal((await fresh('reconcile',s)).result.state,'unknown');assert.equal((await metrics()).posts,before.posts);assert.equal((await metrics()).writes,before.writes);assert.equal((await fresh('get',s)).result.outcome.resultDigest,s.outcome.resultDigest);});
test('19 mutable notification projection cannot redirect immutable recipient, result digest or run binding',async()=>{const s=await seed();const before=await metrics();for(const patch of [{recipientId:f.actors[2]},{resultDigest:bindingDigest('wrong')},{runId:randomUUID()},{notificationId:randomUUID()},{attempts:4},{deepLink:'/tasks/'+randomUUID()}]){await f.admin.query('UPDATE fabric.recovery_notifications SET record=$4 WHERE tenant_id=$1 AND space_id=$2 AND notification_id=$3',[f.tenant,f.space,s.notification.notificationId,JSON.stringify({...s.notification,...patch})]);try{await assert.rejects(notifications.get(await f.scopeFor(1),s.notification.notificationId));await assert.rejects(notifications.send(await f.scopeFor(1),s.notification.notificationId,endpoint));}finally{await f.admin.query('UPDATE fabric.recovery_notifications SET record=$4 WHERE tenant_id=$1 AND space_id=$2 AND notification_id=$3',[f.tenant,f.space,s.notification.notificationId,JSON.stringify(s.notification)]);}}assert.equal((await metrics()).posts,before.posts);assert.equal((await results.get(await f.scopeFor(1),s.runId)).outcome?.resultDigest,s.outcome.resultDigest);});
