import {canonicalDigest,nonEmptyString,nonNegativeInteger,record,requireCondition,type Clock,type ScopeRef} from '../../../engine/contracts/src/identity.js';
import {parseScope} from '../../../engine/contracts/src/task-envelope.js';
import type {ToolDefinition} from '../../../engine/contracts/src/adapters.js';
export interface PinnedTool {definition:ToolDefinition;dependencies:{name:string;version:string;digest:string}[];credentialRefs:string[];expiresAt:number}
export interface ToolAdmission {scope:ScopeRef;actorId:string;toolId:string;version:string;digest:string;grants:string[];capabilities:string[];resourceKind:string;effectCeiling:('read'|'model'|'write'|'computer')[];maxUnits:number}
export interface ToolAuthority {grants:string[];capabilities:string[];effectCeiling:('read'|'model'|'write'|'computer')[];maxUnits:number}
function strings(v:unknown):string[]{requireCondition(Array.isArray(v),'INVALID_SCHEMA','Explicit string list required');return v.map(x=>nonEmptyString(x));}
function sha(v:unknown):string{const s=nonEmptyString(v);requireCondition(/^(sha256:)?[a-f0-9]{64}$/.test(s),'INVALID_SCHEMA','Pinned digest required');return s;}
export function parsePinnedTool(value:unknown):PinnedTool{
 canonicalDigest(value);const p=record(value,['definition','dependencies','credentialRefs','expiresAt']),d=record(p.definition,['toolId','version','digest','effect','schemaDigest','resourceKinds','requiredGrants','requiredCapabilities','timeoutMs','maxUnits','reconciliation']);
 requireCondition(['read','model','write','computer'].includes(d.effect as string),'INVALID_SCHEMA','Explicit tool effect required');requireCondition(['lookup','idempotent','none'].includes(d.reconciliation as string),'INVALID_SCHEMA','Explicit reconcile behavior required');
 const definition:ToolDefinition={toolId:nonEmptyString(d.toolId),version:nonEmptyString(d.version),digest:sha(d.digest),effect:d.effect as ToolDefinition['effect'],schemaDigest:sha(d.schemaDigest),resourceKinds:strings(d.resourceKinds),requiredGrants:strings(d.requiredGrants),requiredCapabilities:strings(d.requiredCapabilities),timeoutMs:nonNegativeInteger(d.timeoutMs),maxUnits:nonNegativeInteger(d.maxUnits),reconciliation:d.reconciliation as ToolDefinition['reconciliation']};requireCondition(definition.timeoutMs>0&&definition.resourceKinds.length>0,'INVALID_SCHEMA','Bounded tool timeout/resources required');
 requireCondition(Array.isArray(p.dependencies),'INVALID_SCHEMA','Pinned dependencies required');const dependencies=p.dependencies.map(x=>{const dep=record(x,['name','version','digest']);return {name:nonEmptyString(dep.name),version:nonEmptyString(dep.version),digest:sha(dep.digest)};});const credentialRefs=strings(p.credentialRefs);requireCondition(credentialRefs.every(x=>x.startsWith('vault:')),'INVALID_SCHEMA','Only vault references belong in tool contracts');return {definition,dependencies,credentialRefs,expiresAt:nonNegativeInteger(p.expiresAt)};
}
/** Credentials remain vault references. Tool/MCP identity never supplies authority. */
export class ToolContractRegistry {
 private readonly tools=new Map<string,PinnedTool>();constructor(private readonly clock:Clock,private readonly authorize:(admission:ToolAdmission,tool:PinnedTool)=>ToolAuthority){}
 register(value:PinnedTool):void{const t=parsePinnedTool(value);const id=canonicalDigest({toolId:t.definition.toolId,version:t.definition.version});const old=this.tools.get(id);requireCondition(old===undefined||canonicalDigest(old)===canonicalDigest(t),'IDEMPOTENCY_CONFLICT','Tool/extension pins are immutable');this.tools.set(id,t);}
 admit(value:ToolAdmission):PinnedTool{canonicalDigest(value);record(value,['scope','actorId','toolId','version','digest','grants','capabilities','resourceKind','effectCeiling','maxUnits']);const a=structuredClone(value);a.scope=parseScope(a.scope);for(const v of [a.actorId,a.toolId,a.version,a.resourceKind])nonEmptyString(v);sha(a.digest);strings(a.grants);strings(a.capabilities);strings(a.effectCeiling);nonNegativeInteger(a.maxUnits);const t=this.tools.get(canonicalDigest({toolId:a.toolId,version:a.version}));requireCondition(t!==undefined,'REQUIRED_CAPABILITY_UNSUPPORTED','Pinned tool unavailable');const authority=this.authorize(structuredClone(a),structuredClone(t));canonicalDigest(authority);record(authority,['grants','capabilities','effectCeiling','maxUnits']);strings(authority.grants);strings(authority.capabilities);strings(authority.effectCeiling);nonNegativeInteger(authority.maxUnits);requireCondition(t.expiresAt>nonNegativeInteger(this.clock.now()),'LEASE_EXPIRED','Extension/tool pin lease expired');const d=t.definition;requireCondition(d.digest===a.digest&&d.resourceKinds.includes(a.resourceKind),'CHECK_BINDING_MISMATCH','Exact tool pin and resource type required');requireCondition(d.requiredGrants.every(x=>authority.grants.includes(x))&&d.requiredCapabilities.every(x=>authority.capabilities.includes(x)),'UNAUTHORIZED','Current mandatory tool grants and controls required');requireCondition(a.effectCeiling.includes(d.effect)&&authority.effectCeiling.includes(d.effect),'INTENT_EXCEEDED','Task authority does not allow this tool effect');requireCondition(a.maxUnits<=d.maxUnits&&a.maxUnits<=authority.maxUnits,'BUDGET_EXHAUSTED','Tool request exceeds declared bounded units');return structuredClone(t);}
}
