import {canonicalDigest,nonEmptyString,nonNegativeInteger,record,requireCondition,type Clock,type ScopeRef} from '../../../engine/contracts/src/identity.js';
import {parseScope} from '../../../engine/contracts/src/task-envelope.js';
export interface CheckBinding {scope:ScopeRef;artifactId:string;artifactDigest:string;candidateId:string;environmentImage:string;dependencyLockDigest:string;checkDefinitionDigest:string;verifierId:string}
export interface CheckReceipt extends CheckBinding {receiptId:string;checkedAt:number;outcome:'pass'|'fail';observationsDigest:string}
export interface CheckExecution {outcome:'pass'|'fail';observationsDigest:string}
export interface RegisteredVerifier {verifierId:string;environmentImage:string;dependencyLockDigest:string;checkDefinitionDigest:string;execute(binding:CheckBinding):CheckExecution}
export interface CheckReceiptPorts {clock:Clock;authorize(scope:ScopeRef):void;assertCandidateCurrent(binding:CheckBinding):void}
function digest(v:unknown):string{const d=nonEmptyString(v);requireCondition(/^(sha256:)?[a-f0-9]{64}$/.test(d),'INVALID_SCHEMA','Exact SHA256 binding required');return d;}
export function parseCheckBinding(v:unknown):CheckBinding{canonicalDigest(v);const p=record(v,['scope','artifactId','artifactDigest','candidateId','environmentImage','dependencyLockDigest','checkDefinitionDigest','verifierId']);return {scope:parseScope(p.scope),artifactId:nonEmptyString(p.artifactId),artifactDigest:digest(p.artifactDigest),candidateId:nonEmptyString(p.candidateId),environmentImage:nonEmptyString(p.environmentImage),dependencyLockDigest:digest(p.dependencyLockDigest),checkDefinitionDigest:digest(p.checkDefinitionDigest),verifierId:nonEmptyString(p.verifierId)};}
/** Owner-held local verifier registry; model claims/imported receipts confer no authority. */
export class CheckReceiptRegistry {
 private readonly verifiers=new Map<string,RegisteredVerifier>();private readonly receipts=new Map<string,CheckReceipt>();
 constructor(private readonly ports:CheckReceiptPorts){}
 registerVerifier(verifier:RegisteredVerifier):void{const identity={verifierId:nonEmptyString(verifier.verifierId),environmentImage:nonEmptyString(verifier.environmentImage),dependencyLockDigest:digest(verifier.dependencyLockDigest),checkDefinitionDigest:digest(verifier.checkDefinitionDigest)};requireCondition(typeof verifier.execute==='function','INVALID_SCHEMA','Actual owner-registered verifier required');requireCondition(!this.verifiers.has(identity.verifierId),'IDEMPOTENCY_CONFLICT','Verifier identity cannot be replaced');this.verifiers.set(identity.verifierId,{...identity,execute:verifier.execute});}
 run(value:CheckBinding,receiptId:string):CheckReceipt{
  const b=parseCheckBinding(value);this.ports.authorize(structuredClone(b.scope));this.ports.assertCandidateCurrent(structuredClone(b));nonEmptyString(receiptId);const existing=this.receipts.get(receiptId);
  requireCondition(existing===undefined||canonicalDigest(bindingOf(existing))===canonicalDigest(b),'IDEMPOTENCY_CONFLICT','Receipt identity immutable');if(existing!==undefined)return this.getCurrent(receiptId,b);
  const verifier=this.verifiers.get(b.verifierId);requireCondition(verifier!==undefined,'REQUIRED_CAPABILITY_UNSUPPORTED','Verifier unavailable; check remains pending');requireCondition(verifier.environmentImage===b.environmentImage&&verifier.dependencyLockDigest===b.dependencyLockDigest&&verifier.checkDefinitionDigest===b.checkDefinitionDigest,'CHECK_BINDING_MISMATCH','Verifier environment, lock and definition must match exactly');
  const result=verifier.execute(structuredClone(b));canonicalDigest(result);record(result,['outcome','observationsDigest']);requireCondition(result.outcome==='pass'||result.outcome==='fail','INVALID_SCHEMA','Verifier outcome required');const observation=digest(result.observationsDigest);this.ports.authorize(structuredClone(b.scope));this.ports.assertCandidateCurrent(structuredClone(b));const receipt={...b,receiptId,checkedAt:nonNegativeInteger(this.ports.clock.now()),outcome:result.outcome,observationsDigest:observation};this.receipts.set(receiptId,receipt);return structuredClone(receipt);
 }
 getCurrent(receiptId:string,value:CheckBinding):CheckReceipt{const b=parseCheckBinding(value);this.ports.authorize(structuredClone(b.scope));this.ports.assertCandidateCurrent(structuredClone(b));const receipt=this.receipts.get(nonEmptyString(receiptId));requireCondition(receipt!==undefined&&canonicalDigest(bindingOf(receipt))===canonicalDigest(b),'CHECK_BINDING_MISMATCH','Only the original current exact-bound receipt is valid');return structuredClone(receipt);}
 requirePass(receiptId:string,binding:CheckBinding):CheckReceipt{const receipt=this.getCurrent(receiptId,binding);requireCondition(receipt.outcome==='pass','CHECK_BINDING_MISMATCH','Protected check has not passed');return receipt;}
}
function bindingOf(r:CheckReceipt):CheckBinding{return {scope:r.scope,artifactId:r.artifactId,artifactDigest:r.artifactDigest,candidateId:r.candidateId,environmentImage:r.environmentImage,dependencyLockDigest:r.dependencyLockDigest,checkDefinitionDigest:r.checkDefinitionDigest,verifierId:r.verifierId};}
