import {canonicalDigest,nonEmptyString,record,requireCondition,type AuthenticatedActorRef,type ScopeRef} from '../../../engine/contracts/src/identity.js';
import {parseScope} from '../../../engine/contracts/src/task-envelope.js';
export interface ChannelMessage {channelId:string;messageId:string;scope:ScopeRef;actorId:string;audience:string[];content:string;explicitTrigger:boolean}
export interface ChannelPorts {authenticate(proof:string,channelId:string):AuthenticatedActorRef;authorize(actor:AuthenticatedActorRef,scope:ScopeRef,audience:string[]):void;isGroup(scope:ScopeRef):boolean}
export interface AdmittedChannelMessage {message:ChannelMessage;actor:AuthenticatedActorRef;automationAllowed:boolean}
/** External channel labels/audience are claims; current trusted membership resolves admission. */
export class ChannelAdapter {
 private readonly messages=new Map<string,AdmittedChannelMessage>();constructor(private readonly ports:ChannelPorts){}
 admit(proof:string,value:ChannelMessage):AdmittedChannelMessage{canonicalDigest(value);const p=record(value,['channelId','messageId','scope','actorId','audience','content','explicitTrigger']);requireCondition(Array.isArray(p.audience)&&p.audience.length>0,'INVALID_SCHEMA','Explicit channel audience required');requireCondition(typeof p.explicitTrigger==='boolean','INVALID_SCHEMA','Explicit group trigger required');const message:ChannelMessage={channelId:nonEmptyString(p.channelId),messageId:nonEmptyString(p.messageId),scope:parseScope(p.scope),actorId:nonEmptyString(p.actorId),audience:p.audience.map(x=>nonEmptyString(x)),content:nonEmptyString(p.content),explicitTrigger:p.explicitTrigger};const actor=this.ports.authenticate(nonEmptyString(proof),message.channelId);requireCondition(actor.tenantId===message.scope.tenantId&&actor.actorId===message.actorId,'UNAUTHORIZED','Trusted channel identity must match claims');this.ports.authorize(structuredClone(actor),structuredClone(message.scope),[...message.audience]);const id=canonicalDigest({scope:message.scope,channel:message.channelId,messageId:message.messageId});const old=this.messages.get(id);requireCondition(old===undefined||canonicalDigest(old.message)===canonicalDigest(message),'IDEMPOTENCY_CONFLICT','Channel message identity immutable');if(old!==undefined)return structuredClone(old);const admitted={message,actor:structuredClone(actor),automationAllowed:!this.ports.isGroup(message.scope)||message.explicitTrigger};this.messages.set(id,admitted);return structuredClone(admitted);}
 notification(proof:string,message:ChannelMessage,result:'sent'|'failed'):{messageId:string;notification:'sent'|'failed'}{requireCondition(result==='sent'||result==='failed','INVALID_SCHEMA','Explicit notification result required');const admitted=this.admit(proof,message);return {messageId:admitted.message.messageId,notification:result};}
}
