import {canonicalDigest,nonEmptyString,record,requireCondition,type ScopeRef} from '../../../engine/contracts/src/identity.js';
import {parseScope} from '../../../engine/contracts/src/task-envelope.js';
import {CheckReceiptRegistry,parseCheckBinding,type CheckBinding} from '../../verification/src/check-receipt.js';
import {EffectBroker} from './dispatch.js';
import {validateOperationInput,type OperationInput,type OperationRecord} from './operation.js';
export interface DeliveryInput {deliveryId:string;scope:ScopeRef;taskId:string;runId:string;artifactId:string;artifactDigest:string;candidateId:string;checks:{receiptId:string;binding:CheckBinding}[];operation:OperationInput}
export interface DeliveryRecord {input:DeliveryInput;state:'prepared'|'unknown'|'delivered'|'failed';notification:'none'|'sent'|'failed';operationId:string}
export interface DeliveryPorts {broker:EffectBroker;checks:CheckReceiptRegistry;authorize(input:DeliveryInput):void;assertAccepted(input:DeliveryInput):void;requiredChecks(input:DeliveryInput):CheckBinding[]}
function key(scope:ScopeRef,id:string):string{const s=parseScope(scope);return canonicalDigest({scope:s,id:nonEmptyString(id)});}
function parseInput(value:unknown):DeliveryInput{canonicalDigest(value);const p=record(value,['deliveryId','scope','taskId','runId','artifactId','artifactDigest','candidateId','checks','operation']);requireCondition(Array.isArray(p.checks),'INVALID_SCHEMA','Explicit check receipts required');const checks=p.checks.map(x=>{const c=record(x,['receiptId','binding']);return {receiptId:nonEmptyString(c.receiptId),binding:parseCheckBinding(c.binding)};});return {deliveryId:nonEmptyString(p.deliveryId),scope:parseScope(p.scope),taskId:nonEmptyString(p.taskId),runId:nonEmptyString(p.runId),artifactId:nonEmptyString(p.artifactId),artifactDigest:nonEmptyString(p.artifactDigest),candidateId:nonEmptyString(p.candidateId),checks,operation:validateOperationInput(p.operation)};}
/** Delivery uses the same effect/approval/budget broker. Notifications never alter its fact. */
export class DeliveryOperationService {
 private readonly rows=new Map<string,DeliveryRecord>();constructor(private readonly ports:DeliveryPorts){}
 prepare(value:DeliveryInput):DeliveryRecord{const input=parseInput(value);this.preconditions(input);const id=key(input.scope,input.deliveryId),old=this.rows.get(id);requireCondition(old===undefined||canonicalDigest(old.input)===canonicalDigest(input),'IDEMPOTENCY_CONFLICT','Delivery identity immutable');if(old!==undefined)return structuredClone(old);this.ports.broker.prepare(input.operation);const row:DeliveryRecord={input,state:'prepared',notification:'none',operationId:input.operation.request.operationId};this.rows.set(id,row);return structuredClone(row);}
 get(scope:ScopeRef,id:string):DeliveryRecord{return structuredClone(this.current(scope,id));}
 async dispatch(scope:ScopeRef,id:string):Promise<DeliveryRecord>{const row=this.current(scope,id);this.preconditions(row.input);if(row.state==='delivered'||row.state==='failed')return structuredClone(row);requireCondition(row.state==='prepared','UNKNOWN_EFFECT_REQUIRES_RECONCILIATION','Unknown delivery must reconcile');try{this.apply(row,await this.ports.broker.dispatch(row.input.scope,row.operationId));}catch(error){try{const op=this.ports.broker.inspect(row.input.scope,row.operationId);if(op.state==='dispatched'||op.state==='unknown')row.state='unknown';}catch{row.state='unknown';}throw error;}this.ports.authorize(structuredClone(row.input));return structuredClone(row);}
 async reconcile(scope:ScopeRef,id:string):Promise<DeliveryRecord>{const row=this.current(scope,id);if(row.state==='delivered'||row.state==='failed')return structuredClone(row);this.apply(row,await this.ports.broker.reconcile(row.input.scope,row.operationId));this.ports.authorize(structuredClone(row.input));return structuredClone(row);}
 recordNotification(scope:ScopeRef,id:string,result:'sent'|'failed'):DeliveryRecord{requireCondition(result==='sent'||result==='failed','INVALID_SCHEMA','Explicit notification result required');const row=this.current(scope,id);row.notification=result;return structuredClone(row);}
 private current(scope:ScopeRef,id:string):DeliveryRecord{const row=this.rows.get(key(scope,id));requireCondition(row!==undefined,'UNAUTHORIZED','Current delivery authority required');this.ports.authorize(structuredClone(row.input));return row;}
 private preconditions(input:DeliveryInput):void{
  this.ports.authorize(structuredClone(input));this.ports.assertAccepted(structuredClone(input));const op=input.operation;
  requireCondition(canonicalDigest(op.request.scope)===canonicalDigest(input.scope)&&op.taskId===input.taskId&&op.runId===input.runId&&op.request.artifactDigest===input.artifactDigest,'CHECK_BINDING_MISMATCH','Delivery must bind the exact accepted artifact and Run');
  const required=this.ports.requiredChecks(structuredClone(input)).map(parseCheckBinding);requireCondition(required.length>0&&input.checks.length===required.length,'CHECK_BINDING_MISMATCH','Protected checks cannot be disabled by the worker');const seen=new Set<string>();
  for(const binding of required){requireCondition(canonicalDigest(binding.scope)===canonicalDigest(input.scope)&&binding.artifactId===input.artifactId&&binding.artifactDigest===input.artifactDigest&&binding.candidateId===input.candidateId,'CHECK_BINDING_MISMATCH','Server-required checks must bind this exact candidate');const digest=canonicalDigest(binding);requireCondition(!seen.has(digest),'CHECK_BINDING_MISMATCH','Duplicate protected checks');seen.add(digest);const receipt=input.checks.find(x=>canonicalDigest(x.binding)===digest);requireCondition(receipt!==undefined,'CHECK_BINDING_MISMATCH','Protected check missing');this.ports.checks.requirePass(receipt.receiptId,binding);}
 }
 private apply(row:DeliveryRecord,op:OperationRecord):void{requireCondition(op.input.request.operationId===row.operationId&&canonicalDigest(op.input)===canonicalDigest(row.input.operation),'IDEMPOTENCY_CONFLICT','Delivery operation binding drift');row.state=op.state==='committed'?'delivered':op.state==='safely-failed'?'failed':op.state==='unknown'||op.state==='dispatched'?'unknown':'prepared';}
}
