import {createHash,randomUUID} from 'node:crypto';
import {assertUuid,assertRevision} from '../../g1-foundations/src/contracts.js';
import {CurrentAudienceVerifier} from './audience.js';
import {IdentityError,type ApprovalRepositoryPort,type ApprovalRecord,type ApprovalReceipt,type ApprovalCommitLookup,type AsyncUnitOfWork,type ScopeBindingLookup,type AudienceVerifier,type ExactApprovalBinding,type CreateApprovalInput,type ConsumeApprovalInput,type SqlTransaction,type VerifiedScope} from './contracts.js';
function canonical(x:unknown):string {if(x===null||typeof x!=='object')return JSON.stringify(x);if(Array.isArray(x))return '['+x.map(canonical).join(',')+']';return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+canonical((x as Record<string,unknown>)[k])).join(',')+'}';}
export function approvalDigest(binding:ExactApprovalBinding):string {validate(binding);return 'sha256:'+createHash('sha256').update(canonical(binding)).digest('hex');}
function validate(b:ExactApprovalBinding):void {
 const keys=['tenantId','spaceId','taskId','runId','operationId','target','action','argsDigest','artifactVersion','policyRevision','requirementsRevision','sourceAudience','limits','expiresAt'];if(Object.keys(b).sort().join(',')!==keys.sort().join(','))throw new IdentityError('INVALID_INPUT');
 for(const id of [b.tenantId,b.spaceId,b.taskId,b.runId,b.operationId,b.sourceAudience.sourceSpaceId,b.sourceAudience.sourceTaskId,b.sourceAudience.destinationSpaceId,...b.sourceAudience.recipientActorIds])assertUuid(id);
 for(const n of [b.artifactVersion,b.policyRevision,b.requirementsRevision,b.limits.maxOperations,b.limits.maxCostMicrounits])assertRevision(n);
 if(b.artifactVersion<1||b.limits.maxOperations<1||!Number.isFinite(Date.parse(b.expiresAt))||!/^sha256:[a-f0-9]{64}$/.test(b.argsDigest)||!/^sha256:[a-f0-9]{64}$/.test(b.sourceAudience.revisionDigest)||typeof b.target!=='string'||!b.target||b.target.length>2048||typeof b.action!=='string'||!b.action||b.action.length>256)throw new IdentityError('INVALID_INPUT');
}
type Party={actorId:string;grant:string;identity:unknown;human:boolean};
type Row={tenant_id:string;space_id:string;approval_id:string;requester_id:string;executor_id:string;approver_id:string|null;request_identity:Record<string,unknown>;approver_identity:Record<string,unknown>|null;binding:ExactApprovalBinding;binding_digest:string;state:ApprovalRecord['state']} & Record<string,unknown>;
function record(r:Row):ApprovalRecord{return {approvalId:r.approval_id,requesterId:r.requester_id,executorId:r.executor_id,approverId:r.approver_id,binding:r.binding,bindingDigest:r.binding_digest,state:r.state};}
function validateKey(key:string):void{if(typeof key!=='string'||key.length<1||key.length>256)throw new IdentityError('INVALID_INPUT');}
export interface ExactApprovalRepositoryOptions{uow:AsyncUnitOfWork;bindingFor:ScopeBindingLookup;audience?:AudienceVerifier;beforeAudit?:()=>void}
export class ExactApprovalRepository implements ApprovalRepositoryPort{
 readonly audience:AudienceVerifier;
 constructor(readonly options:ExactApprovalRepositoryOptions){this.audience=options.audience??new CurrentAudienceVerifier();}
 private async lockCommand(tx:SqlTransaction,scope:VerifiedScope,key:string):Promise<void>{
  // Include the receipt namespace, but never the digest: conflicting requests
  // for the same original key must serialize too. Hash collisions only wait.
  const hash=createHash('sha256').update(JSON.stringify(['fabric.approval_receipts',scope.tenantId,scope.spaceId,scope.actorId,key])).digest('hex').slice(0,16);
  const lockId=BigInt.asIntN(64,BigInt('0x'+hash)).toString();
  try{await tx.query('SELECT pg_advisory_xact_lock($1::bigint)',[lockId]);}
  catch{throw new IdentityError('UNKNOWN_COMMIT','Original command is unresolved; lookup the original key, never replay');}
 }
 private scope(scope:VerifiedScope,b:ExactApprovalBinding):void{if(b.tenantId!==scope.tenantId||b.spaceId!==scope.spaceId)throw new IdentityError('UNAUTHORIZED');}
 private async current(tx:SqlTransaction,scope:VerifiedScope,b:ExactApprovalBinding):Promise<void>{
  this.scope(scope,b);const r=(await tx.query('SELECT fabric.identity_target_current($1,$2,$3) AS current',[b.target,b.taskId,b.runId])).rows[0]?.current as Record<string,unknown>|null;
  if(!r||Number(r.requirementsRevision)!==b.requirementsRevision||Number(r.runRequirementsRevision)!==b.requirementsRevision||Number(r.policyRevision)!==b.policyRevision||Number(r.artifactVersion)!==b.artifactVersion||r.argsDigest!==b.argsDigest)throw new IdentityError('APPROVAL_CONFLICT');
  await this.audience.verify(tx,scope,b.sourceAudience);
 }
 private async parties(tx:SqlTransaction,parties:Party[]):Promise<void>{const r=await tx.query('SELECT fabric.identity_parties_current($1::jsonb) AS valid',[JSON.stringify(parties)]);if(r.rows[0]?.valid!==true)throw new IdentityError('UNAUTHORIZED');}
 private async live(tx:SqlTransaction,b:ExactApprovalBinding):Promise<void>{if((await tx.query('SELECT $1::timestamptz>clock_timestamp() AS valid',[b.expiresAt])).rows[0]?.valid!==true)throw new IdentityError('APPROVAL_CONFLICT');}
 private async get(tx:SqlTransaction,scope:VerifiedScope,id:string):Promise<Row>{assertUuid(id);const row=(await tx.query<Row>('SELECT * FROM fabric.exact_approvals WHERE tenant_id=$1 AND space_id=$2 AND approval_id=$3 FOR UPDATE',[scope.tenantId,scope.spaceId,id])).rows[0];if(!row)throw new IdentityError('APPROVAL_REQUIRED');return row;}
 async create(scope:VerifiedScope,input:CreateApprovalInput):Promise<ApprovalRecord>{assertUuid(input.approvalId);assertUuid(input.executorId);const digest=approvalDigest(input.binding);this.scope(scope,input.binding);if(scope.actorId===input.executorId)throw new IdentityError('UNAUTHORIZED');const identity=this.options.bindingFor(scope);
  return this.options.uow.withScope(scope,async tx=>{await this.current(tx,scope,input.binding);const parties:Party[]=[{actorId:scope.actorId,grant:'task:write',identity,human:false}];await this.parties(tx,parties);await this.live(tx,input.binding);const r=await tx.query<Row>("INSERT INTO fabric.exact_approvals(tenant_id,space_id,approval_id,requester_id,executor_id,request_identity,binding,binding_digest,state) VALUES($1,$2,$3,$4,$5,$6::jsonb,$7::jsonb,$8,'pending') RETURNING *",[scope.tenantId,scope.spaceId,input.approvalId,scope.actorId,input.executorId,JSON.stringify(identity),JSON.stringify(input.binding),digest]);await this.parties(tx,parties);await this.live(tx,input.binding);return record(r.rows[0]!);});
 }
 async approve(scope:VerifiedScope,id:string,digest:string):Promise<ApprovalRecord>{const identity=this.options.bindingFor(scope);return this.options.uow.withScope(scope,async tx=>{const r=await this.get(tx,scope,id);if(r.binding_digest!==digest||r.state!=='pending'||[r.requester_id,r.executor_id].includes(scope.actorId)||identity.principalKind!=='human')throw new IdentityError('APPROVAL_CONFLICT');await this.current(tx,scope,r.binding);const parties:Party[]=[{actorId:r.requester_id,grant:'task:write',identity:r.request_identity,human:false},{actorId:scope.actorId,grant:'approval:approve',identity,human:true}];await this.parties(tx,parties);await this.live(tx,r.binding);const updated=(await tx.query<Row>("UPDATE fabric.exact_approvals SET approver_id=$4,approver_identity=$5::jsonb,state='approved' WHERE tenant_id=$1 AND space_id=$2 AND approval_id=$3 RETURNING *",[scope.tenantId,scope.spaceId,id,scope.actorId,JSON.stringify(identity)])).rows[0]!;await this.parties(tx,parties);await this.live(tx,r.binding);return record(updated);});}
 async consume(scope:VerifiedScope,input:ConsumeApprovalInput):Promise<ApprovalReceipt>{validateKey(input.idempotencyKey);const digest=approvalDigest(input.binding);const identity=this.options.bindingFor(scope);return this.options.uow.withScope(scope,async tx=>{
  // The same key lock in lookup waits through COMMIT/ROLLBACK before reading.
  await this.lockCommand(tx,scope,input.idempotencyKey);
  const r=await this.get(tx,scope,input.approvalId);if(r.executor_id!==scope.actorId||r.binding_digest!==digest)throw new IdentityError('APPROVAL_CONFLICT');
  const prior=(await tx.query('SELECT receipt,binding_digest FROM fabric.approval_receipts WHERE tenant_id=$1 AND space_id=$2 AND executor_id=$3 AND idempotency_key=$4',[scope.tenantId,scope.spaceId,scope.actorId,input.idempotencyKey])).rows[0];if(prior){if(prior.binding_digest!==digest||(prior.receipt as ApprovalReceipt).approvalId!==input.approvalId)throw new IdentityError('APPROVAL_CONFLICT');return prior.receipt as ApprovalReceipt;}
  if(r.state!=='approved'||r.approver_id===null||new Set([r.requester_id,r.executor_id,r.approver_id]).size!==3)throw new IdentityError('APPROVAL_REQUIRED');await this.current(tx,scope,input.binding);const parties:Party[]=[{actorId:r.requester_id,grant:'task:write',identity:r.request_identity,human:false},{actorId:r.approver_id,grant:'approval:approve',identity:r.approver_identity,human:true},{actorId:r.executor_id,grant:'task:write',identity,human:false}];await this.parties(tx,parties);await this.live(tx,input.binding);
  const receipt:ApprovalReceipt={tenantId:scope.tenantId,spaceId:scope.spaceId,approvalId:r.approval_id,operationId:input.binding.operationId,idempotencyKey:input.idempotencyKey,bindingDigest:digest,auditId:randomUUID(),outboxId:randomUUID(),requesterId:r.requester_id,approverId:r.approver_id,executorId:r.executor_id};
  this.options.beforeAudit?.();await tx.query('INSERT INTO fabric.approval_audit(tenant_id,space_id,audit_id,approval_id,receipt) VALUES($1,$2,$3,$4,$5::jsonb)',[scope.tenantId,scope.spaceId,receipt.auditId,r.approval_id,JSON.stringify(receipt)]);await tx.query('INSERT INTO fabric.approval_outbox(tenant_id,space_id,outbox_id,audit_id,receipt) VALUES($1,$2,$3,$4,$5::jsonb)',[scope.tenantId,scope.spaceId,receipt.outboxId,receipt.auditId,JSON.stringify(receipt)]);await tx.query('INSERT INTO fabric.approval_receipts(tenant_id,space_id,executor_id,idempotency_key,binding_digest,receipt) VALUES($1,$2,$3,$4,$5,$6::jsonb)',[scope.tenantId,scope.spaceId,scope.actorId,input.idempotencyKey,digest,JSON.stringify(receipt)]);await tx.query("UPDATE fabric.exact_approvals SET state='consumed' WHERE tenant_id=$1 AND space_id=$2 AND approval_id=$3",[scope.tenantId,scope.spaceId,r.approval_id]);await this.parties(tx,parties);await this.live(tx,input.binding);return receipt;
 });}
 async lookupCommand(scope:VerifiedScope,key:string,digest:string):Promise<ApprovalCommitLookup>{validateKey(key);if(typeof digest!=='string'||!/^sha256:[a-f0-9]{64}$/.test(digest))throw new IdentityError('INVALID_INPUT');try{return await this.options.uow.withScope(scope,async tx=>{await this.lockCommand(tx,scope,key);const row=(await tx.query('SELECT receipt,binding_digest FROM fabric.approval_receipts WHERE tenant_id=$1 AND space_id=$2 AND executor_id=$3 AND idempotency_key=$4',[scope.tenantId,scope.spaceId,scope.actorId,key])).rows[0];if(!row)return {status:'absent-safe'};if(row.binding_digest!==digest)throw new IdentityError('APPROVAL_CONFLICT');return {status:'committed',receipt:row.receipt as ApprovalReceipt};});}catch(error){if(error instanceof IdentityError&&error.code==='UNKNOWN_COMMIT')return {status:'unknown',nextAction:'lookup-original-key-no-replay'};throw error;}}
}
