import {canonicalDigest,nonEmptyString,nonNegativeInteger,record,requireCondition,type Clock,type ScopeRef} from './identity.js';
import {parseScope} from './task-envelope.js';
import type {MutationLease} from '../../../execution/desktop-broker/src/mutation-barrier-contract.js';
export interface DesktopView {scope:ScopeRef;runId:string;phase:'agent-driving'|'human-driving'|'disconnected'|'awaiting-reconciliation';lease:MutationLease|null;lastUpdate:number}
/** Passive client state. Only current server-acknowledged leases can display a driver. */
export class DesktopClientState {
 private state:DesktopView;constructor(scope:ScopeRef,runId:string,private readonly clock:Clock,private readonly assertLease:(lease:MutationLease)=>void){this.state={scope:parseScope(scope),runId:nonEmptyString(runId),phase:'disconnected',lease:null,lastUpdate:0};}
 inspect():DesktopView{return structuredClone(this.state);}
 disconnect():DesktopView{this.state={...this.state,phase:'disconnected',lease:null};return this.inspect();}
 reconnect():DesktopView{requireCondition(this.state.phase==='disconnected','STALE_FENCE','Reconnect must follow disconnect');this.state={...this.state,phase:'awaiting-reconciliation',lease:null};return this.inspect();}
 acceptLease(value:MutationLease,reconciled:boolean):DesktopView{canonicalDigest(value);record(value,['scope','runId','owner','leaseId','expiresAt','fence']);requireCondition(reconciled===true,'UNKNOWN_EFFECT_REQUIRES_RECONCILIATION','Fresh observation and reconciliation required');requireCondition(canonicalDigest(parseScope(value.scope))===canonicalDigest(this.state.scope)&&value.runId===this.state.runId,'SCOPE_MISMATCH','Driver lease must bind this client Run');requireCondition(value.owner==='agent'||value.owner==='human','INVALID_SCHEMA','Explicit current driver required');nonEmptyString(value.leaseId);requireCondition(nonNegativeInteger(value.expiresAt)>nonNegativeInteger(this.clock.now()),'LEASE_EXPIRED','Input lease expired');record(value.fence,['taskGeneration','runGeneration','runtimeGeneration']);for(const generation of Object.values(value.fence))nonNegativeInteger(generation);this.assertLease(structuredClone(value));this.state={...this.state,phase:value.owner==='agent'?'agent-driving':'human-driving',lease:structuredClone(value),lastUpdate:nonNegativeInteger(this.clock.now())};return this.inspect();}
}
export interface FleetLifecycle {archived:boolean;compute:'active'|'suspended'|'terminated';storage:'retained'|'deleted';computeFeesActive:boolean;storageFeesActive:boolean}
export function reduceFleetLifecycle(value:FleetLifecycle,action:'archive'|'suspend'|'delete'):FleetLifecycle{canonicalDigest(value);const p=record(value,['archived','compute','storage','computeFeesActive','storageFeesActive']);requireCondition(typeof p.archived==='boolean'&&typeof p.computeFeesActive==='boolean'&&typeof p.storageFeesActive==='boolean'&&['active','suspended','terminated'].includes(p.compute as string)&&['retained','deleted'].includes(p.storage as string),'INVALID_SCHEMA','Explicit lifecycle and fee states required');const s=structuredClone(value);if(action==='archive')return {...s,archived:true};if(action==='suspend')return {...s,compute:s.compute==='terminated'?'terminated':'suspended',computeFeesActive:false};requireCondition(action==='delete','INVALID_SCHEMA','Known lifecycle action required');return {archived:true,compute:'terminated',storage:'deleted',computeFeesActive:false,storageFeesActive:false};}
