import {canonicalDigest,nonEmptyString,nonNegativeInteger,record,requireCondition,type ScopeRef} from './identity.js';
import {parseScope,type SourceRef,type Intent} from './task-envelope.js';
import {ClientReplica,type StreamSync} from '../../../apps/api/src/streams/task-events.js';
export interface TaskPresentation {scope:ScopeRef;taskId:string;runId:string;audience:string[];title:string;titleAudience:string[];intent:Intent;executionTarget:string;payerId:string;sources:SourceRef[];draft:'none'|'draft'|'candidate'|'accepted';check:'pending'|'unavailable'|'pass'|'fail';delivery:'not-requested'|'prepared'|'unknown'|'delivered'|'failed';notification:'none'|'sent'|'failed';waiting:{reason:string;resolver:string;nextAction:string}|null;fees:{estimatedUnits:number;settledUnits:number;reservedUnits:number};lastUpdate:number;safeNextAction:string}
export interface VisibleTaskPresentation extends Omit<TaskPresentation,'title'|'titleAudience'> {title:string|null}
export interface PresentationPorts {authorizeView(actorId:string,state:TaskPresentation):void;sourceReadable(actorId:string,source:SourceRef):boolean;authorizeExport(actorId:string,sourceScope:ScopeRef,targetScope:ScopeRef,targetAudience:string[],sources:SourceRef[]):void}
export class PresentationService {
 constructor(private readonly ports:PresentationPorts){}
 view(actorId:string,value:TaskPresentation):VisibleTaskPresentation{canonicalDigest(value);record(value,['scope','taskId','runId','audience','title','titleAudience','intent','executionTarget','payerId','sources','draft','check','delivery','notification','waiting','fees','lastUpdate','safeNextAction']);const s=structuredClone(value);s.scope=parseScope(s.scope);nonEmptyString(actorId);nonEmptyString(s.taskId);nonEmptyString(s.runId);nonEmptyString(s.title);nonEmptyString(s.executionTarget);nonEmptyString(s.payerId);nonEmptyString(s.safeNextAction);nonNegativeInteger(s.lastUpdate);requireCondition(Array.isArray(s.audience)&&Array.isArray(s.titleAudience)&&Array.isArray(s.sources),'INVALID_SCHEMA','Typed audience and sources required');requireCondition(['ask','plan','act'].includes(s.intent)&&['none','draft','candidate','accepted'].includes(s.draft)&&['pending','unavailable','pass','fail'].includes(s.check)&&['not-requested','prepared','unknown','delivered','failed'].includes(s.delivery)&&['none','sent','failed'].includes(s.notification),'INVALID_SCHEMA','Explicit independent presentation statuses required');record(s.fees,['estimatedUnits','settledUnits','reservedUnits']);for(const units of Object.values(s.fees))nonNegativeInteger(units);if(s.waiting!==null){record(s.waiting,['reason','resolver','nextAction']);for(const v of Object.values(s.waiting))nonEmptyString(v);}for(const v of [...s.audience,...s.titleAudience])nonEmptyString(v);requireCondition(s.audience.includes(actorId)&&s.titleAudience.every(x=>s.audience.includes(x)),'UNAUTHORIZED','Current task/title audience required');s.sources=s.sources.map(source=>{record(source,['sourceId','scope','audience','trust','observedAt']);nonEmptyString(source.sourceId);requireCondition(Array.isArray(source.audience)&&source.audience.length>0&&(source.trust==='trusted'||source.trust==='untrusted'),'INVALID_SCHEMA','Typed source audience/trust required');source.audience.forEach(x=>nonEmptyString(x));nonNegativeInteger(source.observedAt);return {...source,scope:parseScope(source.scope)};});this.ports.authorizeView(actorId,structuredClone(s));const {title,titleAudience,...rest}=s;return {...rest,title:titleAudience.includes(actorId)?title:null,sources:s.sources.filter(source=>this.ports.sourceReadable(actorId,structuredClone(source))).map(x=>structuredClone(x))};}
 exportCopy(actorId:string,value:TaskPresentation,targetScope:ScopeRef,targetAudience:string[],copyId:string,content:string):{copyId:string;scope:ScopeRef;audience:string[];title:string|null;content:string;sourceAccess:'none'}{const visible=this.view(actorId,value);const target=parseScope(targetScope);requireCondition(Array.isArray(targetAudience)&&targetAudience.length>0,'INVALID_SCHEMA','Export audience required');targetAudience.forEach(x=>nonEmptyString(x));requireCondition(value.sources.every(s=>this.ports.sourceReadable(actorId,structuredClone(s))),'UNAUTHORIZED','Deleted or revoked source content cannot be exported');this.ports.authorizeExport(actorId,visible.scope,target,[...targetAudience],structuredClone(value.sources));nonEmptyString(content);return {copyId:nonEmptyString(copyId),scope:target,audience:[...targetAudience],title:targetAudience.every(x=>value.titleAudience.includes(x))?visible.title:null,content,sourceAccess:'none'};}
}
export type StopDisplay='Not delivered'|'Awaiting acknowledgment'|'Dispatch fenced';
/** Reuses the authoritative ordered-stream replica; reconnect never submits a draft. */
export class PresentationClient {
 readonly replica:ClientReplica<Record<string,unknown>>;private connected=false;private stop:StopDisplay='Not delivered';
 constructor(scope:ScopeRef,streamId:string){this.replica=new ClientReplica(scope,streamId);}
 get stopDisplay():StopDisplay{return this.stop;}
 get lastUpdate():number|null {const state=this.replica.state;return state===null?null:nonNegativeInteger(state.lastUpdate);}
 get unsentDraft():string|null{return this.replica.unsentDraft;}
 set unsentDraft(value:string|null){requireCondition(value===null||typeof value==='string','INVALID_SCHEMA','Draft text required');this.replica.unsentDraft=value;}
 disconnect():void{this.connected=false;this.stop='Not delivered';}
 reconnect(fetch:(cursor?:import('./events.js').EventCursor)=>StreamSync<Record<string,unknown>>):void{this.connected=false;this.replica.reconnect(fetch);this.connected=true;}
 requestStop(send:()=>{dispatchFenced:boolean}):StopDisplay{if(!this.connected){this.stop='Not delivered';return this.stop;}this.stop='Awaiting acknowledgment';try{const response=send();if(response.dispatchFenced===true)this.stop='Dispatch fenced';}catch{this.stop='Not delivered';}return this.stop;}
}

/** Subsequent modules consume these records; G0 does not schedule or render them. */
export interface DispatchScheduleContract {scope:ScopeRef;scheduleId:string;ownerActorId:string;serviceIdentityActorId:string|null;connectorExpiresAt:number;triggerAt:number;task:import('./task-envelope.js').TaskEnvelope;state:'enabled'|'paused';pauseReason:string|null}
export interface DesignPreviewContract {scope:ScopeRef;artifactId:string;versionId:string;digest:string;baseRevision:number;previewArtifactId:string;status:'draft'|'candidate'|'accepted'}
export interface SourceRetentionContract {scope:ScopeRef;sourceId:string;authorityRevision:number;deletedAt:number|null;dependentRecords:'current'|'require-revalidation'|'tombstoned';brokeredAccess:'allowed'|'revoked';directLinkExpiry:number|null}
