import React,{useEffect,useRef,useState} from 'react';
import { AppState, SafeAreaView, ScrollView, View, Text, TextInput, Pressable, StyleSheet, StatusBar, KeyboardAvoidingView } from 'react-native';
import { createClient,ClientTransportError,type ClientDelivery,type TaskView,type TestIdentity,type LocalSpace,type LocalIntent,type TaskCommand,type CommandResponse } from './src/api';
import {mergeTaskView,applyTaskSync,deliveryMessage} from './src/state';
const accounts={operator:'operator-local-test',approver:'approver-local-test',viewer:'viewer-local-test',outsider:'outsider-local-test'};
type Account=keyof typeof accounts;
let counter=0;const newId=()=>`android-${Date.now().toString(36)}-${++counter}-${Math.random().toString(36).slice(2,10)}`;
function Action({label,onPress,disabled=false,danger=false,testID}:{label:string;onPress:()=>void;disabled?:boolean;danger?:boolean;testID?:string}){return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled}} disabled={disabled} onPress={onPress} testID={testID} style={[styles.button,danger&&styles.danger,disabled&&styles.disabled]}><Text style={[styles.buttonText,danger&&styles.dangerText]}>{label}</Text></Pressable>;}
function Card({title,children}:{title:string;children:React.ReactNode}){return <View style={styles.card}><Text accessibilityRole="header" style={styles.cardTitle}>{title}</Text>{children}</View>;}
export default function App(){
 const client=useRef(createClient()).current;
 const [identity,setIdentity]=useState<TestIdentity|null>(null),[account,setAccount]=useState<Account>('operator'),[password,setPassword]=useState(accounts.operator);
 const [spaces,setSpaces]=useState<LocalSpace[]>([]),[spaceId,setSpaceId]=useState(''),[tasks,setTasks]=useState<TaskView[]>([]),[view,setView]=useState<TaskView|null>(null),[selectedId,setSelectedId]=useState('');
 const [title,setTitle]=useState(''),[input,setInput]=useState(''),[intent,setIntent]=useState<LocalIntent>('ask'),[explicit,setExplicit]=useState(false),[online,setOnline]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[delivery,setDelivery]=useState<ClientDelivery|null>(null),[lastResponse,setLastResponse]=useState<CommandResponse|null>(null);
 const current=useRef<TaskView|null>(null),binding=useRef({spaceId:'',taskId:''}),epoch=useRef(0),pending=useRef(false),manualOffline=useRef(false),drafts=useRef(new Map<string,string>()),draftRef=useRef(''),identityRef=useRef<TestIdentity|null>(null),original=useRef<{commandId:string;spaceId:string;taskId:string|null}|null>(null);
 const key=()=>`${identityRef.current?.actorId??'anonymous'}:${binding.current.spaceId}:${binding.current.taskId||'new'}`;
 function save(){drafts.current.set(key(),draftRef.current);client.unsentDraft=draftRef.current;}
 function setDraft(value:string){draftRef.current=value;setInput(value);client.unsentDraft=value;drafts.current.set(key(),value);}
 function install(v:TaskView|null){current.current=v;setView(v);}
 function accept(v:TaskView){if(binding.current.taskId===v.task.taskId&&binding.current.spaceId===v.task.scope.spaceId)install(mergeTaskView(current.current,v));}
 function failure(e:unknown,read=false){const code=e&&typeof e==='object'&&'code'in e?String(e.code):'ERROR';setError(code+': '+(e instanceof Error?e.message:'Refresh authorized state.'));setOnline(client.connected);setDelivery(client.lastDelivery);if(read&&code==='UNAUTHORIZED'){install(null);setTasks([]);}}
 async function action(fn:()=>Promise<void>){if(pending.current)return;pending.current=true;setBusy(true);setError('');try{await fn();}catch(e){failure(e);}finally{pending.current=false;setBusy(false);setOnline(client.connected);setDelivery(client.lastDelivery);}}
 async function list(id=binding.current.spaceId){if(!id)return;const stamp=epoch.current,rows=await client.listTasks(id);if(stamp===epoch.current&&binding.current.spaceId===id)setTasks(rows);}
 async function pickSpace(id:string){save();++epoch.current;binding.current={spaceId:id,taskId:''};setSpaceId(id);setSelectedId('');setTasks([]);install(null);setLastResponse(null);setDraft(drafts.current.get(key())??'');setExplicit(false);try{await list(id);}catch(e){failure(e,true);}}
 async function pickTask(id:string){save();const stamp=++epoch.current;binding.current.taskId=id;setSelectedId(id);install(null);setLastResponse(null);setDraft(drafts.current.get(key())??'');if(id)try{const v=await client.getTask(id);if(stamp===epoch.current)accept(v);}catch(e){failure(e,true);}}
 async function login(){++epoch.current;const result=await client.login({username:account,password}),rows=await client.spaces();identityRef.current=result.identity;setIdentity(result.identity);setSpaces(rows);binding.current={spaceId:'',taskId:''};setSpaceId('');setSelectedId('');setTasks([]);install(null);setDraft('');setOnline(true);manualOffline.current=false;setNotice('Local-test sign-in confirmed. Choose a Space.');}
 async function create(){if(!binding.current.spaceId)throw Error('Choose a Space.');if(!title.trim()||!draftRef.current.trim())throw Error('A title and request are required.');const target=binding.current.spaceId,stamp=epoch.current,id=newId();original.current={commandId:id,spaceId:target,taskId:null};save();const result=await client.createTask({commandId:id,spaceId:target,title,input:draftRef.current,intent,explicitTrigger:explicit});if(stamp!==epoch.current||binding.current.spaceId!==target)return;binding.current.taskId=result.taskId;setSelectedId(result.taskId);original.current.taskId=result.taskId;setLastResponse(result);if(result.task)accept(result.task);setNotice('Task accepted: '+result.taskId);await list(target);}
 async function command(kind:'reviseTask'|'startRun'|'approve'|'stop'){const v=current.current;if(!v)throw Error('Select an authorized Task.');const target=v.task.taskId,space=v.task.scope.spaceId,stamp=epoch.current,id=newId();original.current={commandId:id,spaceId:space,taskId:target};let payload:TaskCommand;if(kind==='stop')payload={kind,commandId:id,scope:'task',expectedRevision:v.task.revision};else if(kind==='reviseTask')payload={kind,commandId:id,input:draftRef.current,expectedRevision:v.task.revision};else{if(!v.plan)throw Error('No current Plan.');payload={kind,commandId:id,planVersion:v.plan.version,expectedRevision:v.task.revision};}const result=await client.command(target,payload);if(stamp!==epoch.current||binding.current.taskId!==target)return;setLastResponse(result);if(result.task)accept(result.task);setNotice(result.reason??'Request acknowledged: '+id);await list(space);}
 async function reconnect(){const target=binding.current.taskId,stamp=epoch.current;const restored=await client.reconnect(target||undefined);if(stamp!==epoch.current)return;if(restored)accept(restored);await list();setOnline(true);setNotice('Read-only refresh complete. No draft or control was resent.');}
 async function query(){
  const saved=original.current;if(!saved)throw Error('No original command.');
  const stamp=epoch.current,result=await client.queryCommand(saved.commandId,saved.spaceId);
  if(stamp!==epoch.current||binding.current.spaceId!==saved.spaceId||original.current!==saved)return;
  client.lastDelivery={status:'confirmed',commandId:saved.commandId,taskId:result.taskId};setDelivery(client.lastDelivery);
  if(saved.taskId===null&&!binding.current.taskId&&result.task&&result.task.task.scope.spaceId===saved.spaceId){
   save();binding.current.taskId=result.taskId;setSelectedId(result.taskId);saved.taskId=result.taskId;install(null);await list(saved.spaceId);
  }
  setNotice('Original command: '+result.acceptance+' / '+result.completion);
  if(result.task)accept(result.task);if(binding.current.taskId===result.taskId)setLastResponse(result);
 }
 useEffect(()=>{const sub=AppState.addEventListener('change',state=>{if(state!=='active'){save();++epoch.current;client.disconnect();setOnline(false);}else if(identityRef.current&&!manualOffline.current&&!pending.current){void action(reconnect);}});return()=>sub.remove();},[]);
 useEffect(()=>{if(!identity||!online||!selectedId)return;const timer=setInterval(()=>{if(pending.current||AppState.currentState!=='active')return;const stamp=epoch.current,v=current.current;if(!v)return;void client.events(v.task.taskId,v.cursor).then(sync=>{if(stamp===epoch.current)install(applyTaskSync(current.current??v,sync));}).catch(e=>{if(stamp!==epoch.current)return;if(e instanceof ClientTransportError)failure(e,true);else void client.getTask(v.task.taskId).then(fresh=>{if(stamp===epoch.current)accept(fresh);}).catch(err=>failure(err,true));});},1500);return()=>clearInterval(timer);},[identity,online,selectedId]);
 const space=spaces.find(s=>s.scope.spaceId===spaceId),run=view?.runs.at(-1),approval=view?.plan?.approvalRequest;
 return <SafeAreaView style={styles.safe}><StatusBar barStyle="dark-content"/><KeyboardAvoidingView style={styles.safe} behavior="height"><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled">
  <Text accessibilityRole="header" style={styles.heading}>Agent Fabric</Text><Text style={styles.label}>local-test · deterministic-test · synthetic-only</Text><Text style={styles.caption}>Paid API: disabled · Remote: disabled · Full G1 qualification pending</Text><Text testID="connection" style={styles.status}>{online?'Online':'Offline · last known state'}</Text>
  <Card title="Local test identity"><View style={styles.wrap}>{(Object.keys(accounts) as Account[]).map(name=><Action key={name} label={name+(account===name?' ✓':'')} disabled={busy} onPress={()=>{setAccount(name);setPassword(accounts[name]);}}/>)}</View><Text style={styles.caption}>Separate operator and approver accounts; no production SSO.</Text><TextInput accessibilityLabel="Test password" testID="password" style={styles.field} secureTextEntry value={password} onChangeText={setPassword} autoCapitalize="none"/><Action label="Log in" testID="login" disabled={busy} onPress={()=>void action(login)}/>{identity&&<><Text testID="identity" style={styles.body}>{identity.username} · {identity.role} · {identity.actorId}</Text><Action label="Log out" disabled={busy} onPress={()=>void action(async()=>{await client.logout();save();++epoch.current;identityRef.current=null;setIdentity(null);setSpaces([]);setTasks([]);install(null);binding.current={spaceId:'',taskId:''};setSpaceId('');setSelectedId('');setDraft('');setNotice('Logged out. Session token was kept in memory only.');})}/></>}</Card>
  <Card title="Spaces & work">{!identity&&<Text style={styles.caption}>Sign in to fetch authorized Spaces.</Text>}<View style={styles.wrap}>{spaces.map(s=><Action key={s.scope.spaceId} label={s.name+(spaceId===s.scope.spaceId?' ✓':'')} disabled={busy} onPress={()=>void action(()=>pickSpace(s.scope.spaceId))}/>)}</View>{space&&<Text style={styles.caption}>{space.kind} audience · {space.scope.spaceId} · payer {space.payerId}</Text>}<Action label="New task" disabled={busy||!spaceId} onPress={()=>void action(()=>pickTask(''))}/>{spaceId&&tasks.length===0&&<Text style={styles.caption}>No tasks yet.</Text>}{tasks.map(t=><Action key={t.task.taskId} label={`${t.task.title} · ${t.task.taskId}`} testID={'task-'+t.task.taskId} disabled={busy} onPress={()=>void action(()=>pickTask(t.task.taskId))}/>)}<Action label="Refresh tasks" disabled={busy||!identity||!online} onPress={()=>void action(async()=>{await list();if(binding.current.taskId)accept(await client.getTask(binding.current.taskId));})}/></Card>
  {busy&&<Text accessibilityLiveRegion="polite" style={styles.message}>Loading authorized state…</Text>}{notice&&<Text accessibilityLiveRegion="polite" style={styles.message}>{notice}</Text>}{error&&<Text accessibilityRole="alert" testID="error" style={styles.error}>{error}{'\n'}No automatic resend. Refresh or use an authorized account.</Text>}
  <Card title={selectedId?'Update this task':'New task'}>{!selectedId&&<><Text style={styles.caption}>Task title</Text><TextInput accessibilityLabel="Task title" testID="title" style={styles.field} value={title} onChangeText={setTitle} maxLength={256}/><View style={styles.wrap}>{(['ask','plan','act'] as LocalIntent[]).map(mode=><Action key={mode} label={mode+(intent===mode?' ✓':'')+(mode==='act'?' · simulation':'')} onPress={()=>setIntent(mode)}/>)}</View></>}<Text style={styles.caption}>Request / correction</Text><TextInput accessibilityLabel="Request / correction" testID="request" style={[styles.field,styles.multiline]} value={input} onChangeText={setDraft} multiline maxLength={16384} textAlignVertical="top"/><Text style={styles.caption}>Draft not sent. Kept in this session; reconnect never submits it.</Text>{space?.kind==='group'&&!selectedId&&<Action label={'Explicit group trigger: '+(explicit?'on':'off')} onPress={()=>setExplicit(!explicit)}/>}<Action label={selectedId?'Submit correction':'Create task'} testID="submit" disabled={busy||!identity||!spaceId} onPress={()=>void action(selectedId?()=>command('reviseTask'):create)}/></Card>
  {view?<><Card title={view.task.title}><Text testID="task-id" style={styles.mono}>{view.task.taskId}</Text><Text testID="revision" style={styles.body}>Revision {view.task.revision} · generation {view.task.generation}</Text><Text style={styles.caption}>Scope {view.task.scope.spaceId} · owner {view.task.ownerActorId} · payer {view.task.payerId}</Text><Text style={styles.caption}>Sources: {view.task.sourceIds.join(', ')||'None attached'}</Text><Text style={styles.caption}>Last updated: {new Date(view.lastUpdate).toLocaleString()}</Text><Text style={styles.status}>{view.task.stopped?'Dispatch fenced':run?.state??'Pending'}</Text>{run?.waiting&&<Text testID="waiting" style={styles.message}>Waiting: {run.waiting.reason}{'\n'}{run.waiting.nextAction}</Text>}{view.plan&&<><Text style={styles.body}>Plan version {view.plan.version}</Text>{view.plan.steps.map(step=><Text key={step.stepId} style={styles.caption}>{step.description} ({step.effect})</Text>)}</>}{approval&&<><Text style={styles.caption}>Exact target: {approval.target}</Text><Text style={styles.mono}>Binding: {approval.bindingDigest}</Text><Text style={styles.caption}>Expiry: {new Date(approval.expiresAt).toLocaleString()}</Text></>}<Action label="Approve exact plan" testID="approve" disabled={busy||!approval||view.task.stopped} onPress={()=>void action(()=>command('approve'))}/><Text style={styles.caption}>Use the separate approver. The server checks current authority.</Text><Action label="Start synthetic run" testID="start-run" disabled={busy||!view.plan||view.task.stopped} onPress={()=>void action(()=>command('startRun'))}/><Action label="Stop task" testID="stop" danger disabled={busy} onPress={()=>void action(()=>command('stop'))}/><Text style={styles.caption}>Stale progress does not defeat authorized Stop. No workstation process is running.</Text>{lastResponse?.stop&&<Text testID="stop-receipt" style={styles.message}>Request accepted · dispatch fenced · in-flight {lastResponse.stop.inFlight}. Process termination: not applicable.</Text>}</Card><Card title="Result & evidence">{view.result?<><Text style={styles.caption}>Committed local artifact · version {view.result.version}</Text><Text testID="result-digest" selectable style={styles.mono}>{view.result.digest}</Text><Text testID="result-text" selectable style={styles.body}>{view.result.text}</Text></>:<Text style={styles.caption}>No committed result yet. Plan and waiting are separate states.</Text>}<Text style={styles.caption}>Checks: {view.checks.length?view.checks.map(c=>c.outcome+' ('+c.assurance+')').join(', '):'None recorded'}</Text><Text style={styles.caption}>Synthetic run units: {view.runs.reduce((sum,r)=>sum+r.syntheticUnits,0)} · real cost unavailable</Text><Text style={styles.caption}>External delivery is disabled; notifications do not define completion.</Text></Card></>:<Card title="Task state"><Text style={styles.caption}>Select an authorized Task or create one to view actual server state.</Text></Card>}
  <Card title="Connection & delivery"><Text testID="delivery" style={styles.body}>{deliveryMessage(delivery)}</Text>{original.current&&<Text style={styles.mono}>Original command: {original.current.commandId}{'\n'}Space: {original.current.spaceId}</Text>}<Action label="Disconnect" disabled={busy||!identity||!online} onPress={()=>{save();++epoch.current;manualOffline.current=true;client.disconnect();setOnline(false);setNotice('Disconnected. Offline Stop is Not delivered.');}}/><Action label="Reconnect (read only)" disabled={busy||!identity} onPress={()=>void action(async()=>{manualOffline.current=false;await reconnect();})}/><Action label="Query original command" disabled={busy||!identity||!online||!original.current} onPress={()=>void action(query)}/></Card>
  <Text style={styles.footer}>G1-local: Android development build. Real devices, signed distribution, SSO, remote execution and actual model billing remain pending.</Text>
 </ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#F3F5F8'},page:{padding:16,paddingBottom:36,gap:14},heading:{fontSize:28,fontWeight:'700',color:'#111A22'},label:{fontSize:13,fontWeight:'600',color:'#2745D0'},caption:{fontSize:13,lineHeight:20,color:'#46515C',marginVertical:5},body:{fontSize:15,lineHeight:22,color:'#111A22',marginVertical:6},card:{backgroundColor:'#FFFFFF',borderColor:'#DCE1E8',borderWidth:1,borderRadius:16,padding:16,gap:8},cardTitle:{fontSize:18,fontWeight:'600',color:'#111A22',marginBottom:6},wrap:{flexDirection:'row',flexWrap:'wrap',gap:8},button:{minHeight:48,borderRadius:24,paddingHorizontal:18,paddingVertical:13,justifyContent:'center',backgroundColor:'#2745D0',marginVertical:3},buttonText:{fontSize:14,fontWeight:'600',color:'#FFFFFF'},danger:{backgroundColor:'#FADDDB',borderColor:'#9B1F26',borderWidth:1},dangerText:{color:'#9B1F26'},disabled:{opacity:.5},field:{minHeight:48,borderColor:'#9BA9B8',borderWidth:1,borderRadius:12,padding:12,color:'#111A22',backgroundColor:'#FFFFFF',fontSize:15},multiline:{minHeight:120},status:{fontSize:14,fontWeight:'600',color:'#2745D0',paddingVertical:6},message:{backgroundColor:'#E4E9FB',borderRadius:12,padding:12,color:'#1B31A3',fontSize:14,lineHeight:21},error:{backgroundColor:'#FADDDB',borderRadius:12,padding:12,color:'#9B1F26',fontSize:14,lineHeight:21},mono:{fontFamily:'monospace',fontSize:11,lineHeight:18,color:'#46515C',marginVertical:5},footer:{fontSize:12,lineHeight:19,color:'#46515C'}});
