import test from 'node:test';
import assert from 'node:assert/strict';
import { mergeTaskView, applyTaskSync, deliveryMessage, LocalClient } from '../node_modules/.cache/ssr/main.js';
const labels={schemaVersion:1,modelMode:'deterministic-test',effectMode:'synthetic-only',paidCallsAllowed:false,remoteAllowed:false};
function view(revision=2,sequence=3){return {...labels,task:{taskId:'task-a',scope:{tenantId:'tenant-a',spaceId:'space-a'},revision,generation:0},authorityRevision:1,cursor:{streamId:'task-a',sequence,generation:0},runs:[],lastUpdate:1};}
const response=v=>new Response(JSON.stringify(v),{status:200,headers:{'Content-Type':'application/json'}});
test('Web keeps immutable scope and refuses stale revision/cursor rollback',()=>{const current=view();assert.equal(mergeTaskView(current,view(1,2)),current);assert.equal(mergeTaskView(current,{...view(),authorityRevision:0}),current);assert.throws(()=>mergeTaskView(current,{...view(),task:{...current.task,scope:{tenantId:'tenant-a',spaceId:'other'}}}),/mismatch/);assert.equal(mergeTaskView(current,view(3,4)).task.revision,3);});
test('Web event recovery handles duplicates but refuses gaps and mixed streams',()=>{const current=view(),next=view(3,4),event={taskId:'task-a',scope:current.task.scope,generation:0,sequence:4,task:next};const delta={kind:'delta',scope:current.task.scope,authorityRevision:1,events:[event,event],cursor:next.cursor};assert.equal(applyTaskSync(current,delta).task.revision,3);assert.throws(()=>applyTaskSync(current,{...delta,events:[{...event,sequence:5}]}),/gap/);assert.throws(()=>applyTaskSync(current,{...delta,cursor:{...delta.cursor,generation:1}}),/Snapshot/);assert.throws(()=>applyTaskSync(current,{...delta,events:[{...event,taskId:'other'}]}),/binding/);});
test('Web offline Stop is not delivered and reconnect never submits its draft or command',async()=>{const calls=[];const client=new LocalClient('http://127.0.0.1:8791',{fetch:async(url,init)=>{calls.push({url,method:init.method});return response(url.endsWith('/login')?{...labels,token:'abcdefghijklmnop',identity:{identityMode:'local-test'}}:view());}});await client.login({username:'operator',password:'operator-local-test'});calls.length=0;client.unsentDraft='Unsent correction';client.disconnect();await assert.rejects(()=>client.command('task-a',{kind:'stop',scope:'task',commandId:'original-stop'}),e=>e.code==='NOT_DELIVERED');assert.equal(calls.length,0);assert.match(deliveryMessage(client.lastDelivery),/^Not delivered/);await client.reconnect('task-a');assert.equal(calls.length,1);assert.equal(calls[0].method,'GET');assert.equal(client.unsentDraft,'Unsent correction');assert.equal(client.lastDelivery.commandId,'original-stop');});
test('Web retains unknown acknowledgement identity and queries it without replay',async()=>{let posts=0;const client=new LocalClient('http://127.0.0.1:8791',{fetch:async(url,init)=>{if(url.endsWith('/login'))return response({...labels,token:'abcdefghijklmnop',identity:{identityMode:'local-test'}});if(init.method==='POST'){posts++;throw Error('lost ack');}if(url.includes('/commands/'))return response({...labels,commandId:'lost-stop',taskId:'task-a',task:view(),acceptance:'accepted',completion:'committed'});return response(view());}});await client.login({username:'operator',password:'operator-local-test'});await assert.rejects(()=>client.command('task-a',{kind:'stop',scope:'task',commandId:'lost-stop'}),e=>e.code==='UNKNOWN_DELIVERY');assert.equal(posts,1);assert.match(deliveryMessage(client.lastDelivery),/Delivery unknown/);await client.reconnect('task-a');await client.queryCommand('lost-stop','space-a');assert.equal(posts,1);assert.equal(client.lastDelivery.commandId,'lost-stop');});
test('Web denies nonlocal transport and test-mode downgrade',()=>{assert.throws(()=>new LocalClient('https://provider.invalid'),e=>e.code==='LOCAL_POLICY_VIOLATION');assert.throws(()=>mergeTaskView(null,{...view(),paidCallsAllowed:true}),/Unsupported/);});
