import {canonicalDigest,nonEmptyString,nonNegativeInteger,record,requireCondition,type ScopeRef} from '../../../engine/contracts/src/identity.js';
import {parseScope} from '../../../engine/contracts/src/task-envelope.js';
import type {RetryBudget} from '../../../engine/contracts/src/budget.js';
export interface RetryBinding {scope:ScopeRef;actorId:string;runId:string;operationId:string;retryKey:string;maxAttempts:number}
export interface RetryAttempt {attemptId:string;ordinal:number;layer:'engine'|'gateway';granted:boolean}
interface RetryRecord {binding:RetryBinding;attempts:RetryAttempt[];unknownUsage:boolean}
function parseBinding(value:unknown):RetryBinding{canonicalDigest(value);const p=record(value,['scope','actorId','runId','operationId','retryKey','maxAttempts']);const b={scope:parseScope(p.scope),actorId:nonEmptyString(p.actorId),runId:nonEmptyString(p.runId),operationId:nonEmptyString(p.operationId),retryKey:nonEmptyString(p.retryKey),maxAttempts:nonNegativeInteger(p.maxAttempts)};requireCondition(b.maxAttempts>0,'INVALID_SCHEMA','Retry allowance includes a bounded first attempt');return b;}
/** Engine and gateway must share this single owner; unknown usage disables retries. */
export class SharedRetryBudget {
 private readonly rows=new Map<string,RetryRecord>();private readonly operationKeys=new Map<string,string>();
 constructor(private readonly authorize:(binding:RetryBinding)=>void,private readonly verifyKnownUsage:(binding:RetryBinding,receiptId:string)=>boolean){}
 create(value:RetryBinding):RetryBudget{const b=parseBinding(value);this.authorize(structuredClone(b));const op=canonicalDigest({scope:b.scope,runId:b.runId,operationId:b.operationId});const oldKey=this.operationKeys.get(op);requireCondition(oldKey===undefined||oldKey===b.retryKey,'IDEMPOTENCY_CONFLICT','One operation cannot mint a second retry allowance');const old=this.rows.get(b.retryKey);requireCondition(old===undefined||canonicalDigest(old.binding)===canonicalDigest(b),'IDEMPOTENCY_CONFLICT','Retry identity and ceiling are immutable');if(old===undefined){this.rows.set(b.retryKey,{binding:b,attempts:[],unknownUsage:false});this.operationKeys.set(op,b.retryKey);}return this.inspect(b.retryKey);}
 inspect(retryKey:string):RetryBudget{const row=this.get(retryKey);return {retryKey:row.binding.retryKey,maxAttempts:row.binding.maxAttempts,usedAttempts:row.attempts.length,unknownUsage:row.unknownUsage};}
 take(retryKey:string,attemptId:string,layer:'engine'|'gateway'):RetryAttempt{nonEmptyString(attemptId);requireCondition(layer==='engine'||layer==='gateway','INVALID_SCHEMA','Known retry layer required');const row=this.get(retryKey);const prior=row.attempts.find(x=>x.attemptId===attemptId);if(prior!==undefined)return {...structuredClone(prior),granted:false};requireCondition(!row.unknownUsage,'UNKNOWN_EFFECT_REQUIRES_RECONCILIATION','Reconcile unknown usage before any retry');requireCondition(row.attempts.length<row.binding.maxAttempts,'BUDGET_EXHAUSTED','Shared retry allowance exhausted');const attempt={attemptId,ordinal:row.attempts.length+1,layer,granted:true};row.attempts.push(attempt);return structuredClone(attempt);}
 markUnknown(retryKey:string):RetryBudget{const row=this.get(retryKey);row.unknownUsage=true;return this.inspect(retryKey);}
 reconcileKnown(retryKey:string,receiptId:string):RetryBudget{nonEmptyString(receiptId);const row=this.get(retryKey);requireCondition(this.verifyKnownUsage(structuredClone(row.binding),receiptId)===true,'CHECK_BINDING_MISMATCH','A current trusted usage receipt must bind the original operation');row.unknownUsage=false;return this.inspect(retryKey);}
 private get(retryKey:string):RetryRecord{const row=this.rows.get(nonEmptyString(retryKey));requireCondition(row!==undefined,'UNAUTHORIZED','Trusted retry admission required');this.authorize(structuredClone(row.binding));return row;}
}
