import test,{before,after} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID,createHash} from 'node:crypto';
import {spawn,type ChildProcessWithoutNullStreams} from 'node:child_process';
import {resolve} from 'node:path';
import pg from 'pg';
import {createScopeVerifier,type VerifiedScope} from '../../g1-foundations/src/contracts.js';
import {PostgresUnitOfWork} from '../../g1-foundations/src/postgres-uow.js';
import {AuthenticatedUnitOfWork,createPostgresAuthorityLookup,createPostgresIdpSessionStore} from '../src/authenticated-uow.js';
import {migrateIdentity} from '../src/migration.js';
import {createIdentityScopeVerifier} from '../src/current-authority.js';
import {verifyAccessToken} from '../src/token-verifier.js';
import {beginTestAuthorization,completeTestAuthorization} from '../src/test-idp.js';
import type {AuthenticatedBinding} from '../src/contracts.js';
export async function createFixture(){
 const url=process.env.IDENTITY_DATABASE_URL;if(!url)throw new Error('Actual owned PostgreSQL required; no mocks/skips');
 const admin=new pg.Pool({connectionString:url,max:5,connectionTimeoutMillis:2000});await migrateIdentity(admin,{ownedSyntheticDatabase:true});
 const tenant=randomUUID(),space=randomUUID(),source=randomUUID(),task=randomUUID(),sourceTask=randomUUID(),run=randomUUID(),sourcePayer=randomUUID(),actors=[randomUUID(),randomUUID(),randomUUID(),randomUUID()];const password=randomUUID();const base='i_'+randomUUID().replaceAll('-','');
 const names={controller:base+'_c',idp:base+'_i',worker:base+'_w'};for(const [k,name] of Object.entries(names)){await admin.query(`CREATE ROLE ${name} LOGIN INHERIT NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE PASSWORD '${password}'`);await admin.query(`GRANT ${k==='controller'?'fabric_controller':k==='idp'?'fabric_test_idp':'fabric_worker'} TO ${name}`);}
 const connection=(name:string)=>{const u=new URL(url);u.username=name;u.password=password;return u.href;};const controller=new pg.Pool({connectionString:connection(names.controller),max:5}),idp=new pg.Pool({connectionString:connection(names.idp),max:2}),worker=new pg.Pool({connectionString:connection(names.worker),max:1});
 await admin.query('INSERT INTO fabric.tenants(tenant_id) VALUES($1)',[tenant]);for(const a of [...actors,sourcePayer])await admin.query('INSERT INTO fabric.actors(tenant_id,actor_id,identity_subject) VALUES($1,$2,$3)',[tenant,a,a]);
 for(const s of [space,source]){await admin.query("INSERT INTO fabric.spaces(tenant_id,space_id,owner_actor_id,payer_actor_id,data_namespace_id,compute_namespace_id,authority_revision,lifecycle) VALUES($1,$2,$3,$4,$5,$6,1,'active')",[tenant,s,actors[0],s===source?sourcePayer:actors[0],randomUUID(),randomUUID()]);for(const a of actors)await admin.query('INSERT INTO fabric.memberships(tenant_id,space_id,actor_id,revision,grants) VALUES($1,$2,$3,1,$4)',[tenant,s,a,JSON.stringify(['task:read','task:write','approval:approve'])]);}
 for(const [s,t] of [[space,task],[source,sourceTask]])await admin.query("INSERT INTO fabric.tasks(tenant_id,space_id,task_id,actor_id,revision,state,requirements) VALUES($1,$2,$3,$4,1,'planned','{}')",[tenant,s,t,actors[0]]);
 await admin.query("INSERT INTO fabric.runs(tenant_id,space_id,run_id,task_id,attempt,requirement_revision,version_pins,generation,state) VALUES($1,$2,$3,$4,1,1,'{}',1,'planned')",[tenant,space,run,task]);
 const issuer='http://127.0.0.1/'+randomUUID();const sessions=actors.map(()=>randomUUID());for(let i=0;i<actors.length;i++){await admin.query('INSERT INTO fabric.identities(issuer,subject,tenant_id,actor_id,principal_kind) VALUES($1,$2,$3,$4,$5)',[issuer,actors[i],tenant,actors[i],i===3?'service':'human']);await createPostgresIdpSessionStore(idp).create({issuer,subject:actors[i]!,sessionId:sessions[i]!,expiresAt:new Date(Date.now()+600000).toISOString(),revokedAt:null});}
 const lookup=createPostgresAuthorityLookup(controller);const bindings=new WeakMap<object,AuthenticatedBinding>();
 async function scopeFor(index:number):Promise<VerifiedScope>{const identity={issuer,subject:actors[index]!,sessionId:sessions[index]!};const v=createScopeVerifier(async r=>r.sessionCredential===sessions[index]?lookup(identity,r):null);const s=await v.verify({tenantId:tenant,spaceId:space,sessionCredential:sessions[index]!});bindings.set(s,{...identity,actorId:actors[index]!,principalKind:index===3?'service':'human',tokenExpiresAt:Math.floor(Date.now()/1000)+600});return s;}
 function bindingFor(s:VerifiedScope){const b=bindings.get(s);if(!b)throw new Error('unissued identity scope');return b;}
 const foundation=new PostgresUnitOfWork(controller),uow=new AuthenticatedUnitOfWork({foundation,bindingFor});
 return {admin,controller,idp,worker,idpDsn:connection(names.idp),tenant,space,source,sourcePayer,task,sourceTask,run,actors,issuer,sessions,lookup,scopeFor,bindingFor,uow,foundation,async close(){await Promise.all([controller.end(),idp.end(),worker.end()]);for(const n of Object.values(names))await admin.query(`DROP ROLE ${n}`);await admin.end();}};
}
if(process.argv[1]?.endsWith('identity-postgres.test.js')){
 let f:Awaited<ReturnType<typeof createFixture>>,scope:VerifiedScope;
 before(async()=>{f=await createFixture();scope=await f.scopeFor(0);});after(async()=>{await f?.close();});
 test('IDENTITY/separate-ledger-forward-recovery',async()=>{await migrateIdentity(f.admin,{ownedSyntheticDatabase:true});assert.deepEqual((await f.admin.query('SELECT version FROM public.fabric_foundation_migrations ORDER BY version')).rows.map(x=>x.version),[1,2]);assert.deepEqual((await f.admin.query('SELECT version FROM public.fabric_identity_migrations')).rows.map(x=>x.version),[3]);const row=(await f.admin.query('SELECT digest FROM public.fabric_identity_migrations')).rows[0];await f.admin.query("UPDATE public.fabric_identity_migrations SET digest='bad'");try{await assert.rejects(migrateIdentity(f.admin,{ownedSyntheticDatabase:true}),/incompatible/);}finally{await f.admin.query('UPDATE public.fabric_identity_migrations SET digest=$1',[row.digest]);}});
 test('IDENTITY/current-PG-issuer-subject-session-map',async()=>{const a=await f.lookup({issuer:f.issuer,subject:f.actors[0]!,sessionId:f.sessions[0]!},{tenantId:f.tenant,spaceId:f.space});assert.equal(a?.actorId,f.actors[0]);assert.equal(await f.lookup({issuer:f.issuer+'/other',subject:f.actors[0]!,sessionId:f.sessions[0]!},{tenantId:f.tenant,spaceId:f.space}),null);assert.equal(await f.lookup({issuer:f.issuer,subject:f.actors[0]!,sessionId:f.sessions[0]!},{tenantId:randomUUID(),spaceId:f.space}),null);await assert.rejects(f.uow.withScope({...scope} as VerifiedScope,async()=>1));});
 test('IDENTITY/real-token-to-current-PG-authority',async()=>{
  const script=resolve(process.cwd().endsWith('g1-identity')?'scripts/test-idp-process.mjs':'g1-identity/scripts/test-idp-process.mjs');const child:ChildProcessWithoutNullStreams=spawn(process.execPath,[script],{env:{...process.env,FABRIC_TEST_IDP_CONFIG:JSON.stringify({clientId:'identity-test',apiAudience:'identity-api',redirectUri:'http://127.0.0.1/callback',users:[{subject:f.actors[0],password:'synthetic'}],sessionDsn:f.idpDsn})},stdio:['pipe','pipe','pipe']});
  let errors='';child.stderr.on('data',d=>errors+=String(d));
  try{const endpoints=await new Promise<Record<string,string>>((res,rej)=>{let text='';const timeout=setTimeout(()=>rej(new Error('IdP child timeout '+errors)),5000);child.stdout.on('data',d=>{text+=String(d);if(text.includes('\n')){clearTimeout(timeout);try{res(JSON.parse(text.split('\n')[0]!));}catch(e){rej(e);}}});child.on('exit',()=>{clearTimeout(timeout);rej(new Error('IdP child exited '+errors));});});
   await f.admin.query("INSERT INTO fabric.identities(issuer,subject,tenant_id,actor_id,principal_kind) VALUES($1,$2,$3,$4,'human')",[endpoints.issuer,f.actors[0],f.tenant,f.actors[0]]);
   const transaction=beginTestAuthorization({issuer:endpoints.issuer!,jwksUrl:endpoints.jwksUrl!,tokenEndpoint:endpoints.tokenEndpoint!,clientId:'identity-test',apiAudience:'identity-api',redirectUri:'http://127.0.0.1/callback'});const {verifier,state,nonce}=transaction;const auth=await fetch(endpoints.authorizationEndpoint!,{method:'POST',redirect:'manual',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({client_id:'identity-test',redirect_uri:'http://127.0.0.1/callback',response_type:'code',code_challenge_method:'S256',code_challenge:createHash('sha256').update(verifier).digest('base64url'),state,nonce,username:f.actors[0]!,password:'synthetic'})});assert.equal(auth.status,302);
   const raw=await completeTestAuthorization({issuer:endpoints.issuer!,jwksUrl:endpoints.jwksUrl!,tokenEndpoint:endpoints.tokenEndpoint!,clientId:'identity-test',apiAudience:'identity-api',redirectUri:'http://127.0.0.1/callback',callbackUrl:auth.headers.get('location')!,state,nonce,verifier,transaction});
   const scopes=createIdentityScopeVerifier({verifyToken:r=>verifyAccessToken(r,{issuer:endpoints.issuer!,apiAudience:'identity-api',jwksUrl:endpoints.jwksUrl!}),lookupAuthority:f.lookup});const issued=await scopes.verify({tenantId:f.tenant,spaceId:f.space,sessionCredential:raw});assert.equal(issued.actorId,f.actors[0]);const authenticated=new AuthenticatedUnitOfWork({foundation:f.foundation,bindingFor:s=>scopes.bindingFor(s)});await authenticated.withScope(issued,async()=>1);const b=scopes.bindingFor(issued);await createPostgresIdpSessionStore(f.idp).revoke(b);await assert.rejects(authenticated.withScope(issued,async()=>1));
  }finally{child.kill('SIGTERM');await new Promise<void>(res=>{if(child.exitCode!==null)res();else{child.once('exit',()=>res());setTimeout(()=>{child.kill('SIGKILL');res();},1500).unref();}});}
 });
 test('IDENTITY/current-membership-payer-lifecycle-revoked',async()=>{for(const [table,where,params] of [['memberships','tenant_id=$1 AND space_id=$2 AND actor_id=$3',[f.tenant,f.space,f.actors[0]]],['actors','tenant_id=$1 AND actor_id=$2',[f.tenant,f.actors[0]]]] as const){await f.admin.query(`UPDATE fabric.${table} SET revoked_at=now() WHERE ${where}`,params as unknown as unknown[]);try{await assert.rejects(f.uow.withScope(scope,async()=>1));}finally{await f.admin.query(`UPDATE fabric.${table} SET revoked_at=NULL WHERE ${where}`,params as unknown as unknown[]);}}await f.admin.query("UPDATE fabric.spaces SET lifecycle='suspended' WHERE tenant_id=$1 AND space_id=$2",[f.tenant,f.space]);try{await assert.rejects(f.uow.withScope(scope,async()=>1));}finally{await f.admin.query("UPDATE fabric.spaces SET lifecycle='active' WHERE tenant_id=$1 AND space_id=$2",[f.tenant,f.space]);}});
 test('IDENTITY/same-transaction-session-revocation-race',async()=>{let entered!:()=>void,release!:()=>void;const gate=new Promise<void>(r=>release=r),ready=new Promise<void>(r=>entered=r);const work=f.uow.withScope(scope,async()=>{entered();await gate;return 1;});await ready;let revoked=false;const revocation=f.idp.query('SELECT fabric.identity_revoke_session($1,$2,$3)',[f.issuer,f.actors[0],f.sessions[0]]).then(()=>{revoked=true;});await new Promise(r=>setTimeout(r,80));assert.equal(revoked,false);release();assert.equal(await work,1);await revocation;await assert.rejects(f.uow.withScope(scope,async()=>1));await f.admin.query('UPDATE fabric.identity_sessions SET revoked_at=NULL WHERE issuer=$1 AND subject=$2 AND sid=$3',[f.issuer,f.actors[0],f.sessions[0]]);const reset=await f.controller.query("SELECT nullif(current_setting('app.actor_id',true),'') AS actor");assert.equal(reset.rows[0].actor,null);});
 test('IDENTITY/role-permissions-worker-denied-idp-narrow',async()=>{const r=(await f.controller.query('SELECT rolsuper,rolbypassrls,rolcreatedb,rolcreaterole FROM pg_roles WHERE rolname=current_user')).rows[0];assert.deepEqual(Object.values(r),[false,false,false,false]);for(const sql of ['SELECT * FROM fabric.identity_sessions','SELECT fabric.identity_authority(\'x\',\'y\',\'z\',null,null)','SELECT * FROM fabric.approval_audit'])await assert.rejects(f.worker.query(sql),/permission denied/);await assert.rejects(f.idp.query('SELECT * FROM fabric.memberships'),/permission denied/);for(const untrusted of [f.worker,f.idp])await assert.rejects(untrusted.query("SELECT fabric.identity_parties_current('[]'::jsonb)"),/permission denied/);await assert.rejects(f.controller.query('UPDATE fabric.approval_audit SET receipt=\'{}\''),/permission denied/);await assert.rejects(f.controller.query('DELETE FROM fabric.approval_audit'),/permission denied/);await assert.rejects(createPostgresIdpSessionStore(f.idp).create({issuer:'unknown',subject:'unknown',sessionId:randomUUID(),expiresAt:new Date(Date.now()+60000).toISOString(),revokedAt:null}),/denied/);});
}
