BEGIN;
DO $$ BEGIN IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname='fabric_test_idp') THEN CREATE ROLE fabric_test_idp NOLOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT;END IF;IF EXISTS(SELECT 1 FROM pg_roles WHERE rolname='fabric_test_idp' AND (rolsuper OR rolbypassrls OR rolcreatedb OR rolcreaterole)) THEN RAISE EXCEPTION 'IdP role incompatible';END IF;END $$;
CREATE TABLE fabric.identities(issuer text NOT NULL,subject text NOT NULL,tenant_id uuid NOT NULL,actor_id uuid NOT NULL,principal_kind text NOT NULL CHECK(principal_kind IN('human','service')),revoked_at timestamptz,PRIMARY KEY(issuer,subject),FOREIGN KEY(tenant_id,actor_id) REFERENCES fabric.actors);
CREATE TABLE fabric.identity_sessions(issuer text NOT NULL,subject text NOT NULL,sid text NOT NULL,expires_at timestamptz NOT NULL,revoked_at timestamptz,PRIMARY KEY(issuer,subject,sid),FOREIGN KEY(issuer,subject) REFERENCES fabric.identities);
CREATE TABLE fabric.identity_target_versions(tenant_id uuid NOT NULL,space_id uuid NOT NULL,target text NOT NULL,artifact_version bigint NOT NULL CHECK(artifact_version>0),args_digest text NOT NULL,PRIMARY KEY(tenant_id,space_id,target),FOREIGN KEY(tenant_id,space_id) REFERENCES fabric.spaces);
CREATE TABLE fabric.exact_approvals(tenant_id uuid NOT NULL,space_id uuid NOT NULL,approval_id uuid NOT NULL,requester_id uuid NOT NULL,executor_id uuid NOT NULL,approver_id uuid,request_identity jsonb NOT NULL,approver_identity jsonb,binding jsonb NOT NULL,binding_digest text NOT NULL,state text NOT NULL CHECK(state IN('pending','approved','consumed')),PRIMARY KEY(tenant_id,space_id,approval_id),CHECK(requester_id<>executor_id),CHECK(approver_id IS NULL OR(approver_id<>requester_id AND approver_id<>executor_id)),FOREIGN KEY(tenant_id,space_id) REFERENCES fabric.spaces);
CREATE TABLE fabric.approval_receipts(tenant_id uuid NOT NULL,space_id uuid NOT NULL,executor_id uuid NOT NULL,idempotency_key text NOT NULL,binding_digest text NOT NULL,receipt jsonb NOT NULL,PRIMARY KEY(tenant_id,space_id,executor_id,idempotency_key),FOREIGN KEY(tenant_id,space_id) REFERENCES fabric.spaces);
CREATE TABLE fabric.approval_audit(tenant_id uuid NOT NULL,space_id uuid NOT NULL,audit_id uuid NOT NULL,approval_id uuid NOT NULL,receipt jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),PRIMARY KEY(tenant_id,space_id,audit_id),FOREIGN KEY(tenant_id,space_id,approval_id) REFERENCES fabric.exact_approvals);
CREATE TABLE fabric.approval_outbox(tenant_id uuid NOT NULL,space_id uuid NOT NULL,outbox_id uuid NOT NULL,audit_id uuid NOT NULL,receipt jsonb NOT NULL,PRIMARY KEY(tenant_id,space_id,outbox_id),FOREIGN KEY(tenant_id,space_id,audit_id) REFERENCES fabric.approval_audit);
CREATE TRIGGER immutable_audit BEFORE UPDATE OR DELETE ON fabric.approval_audit FOR EACH ROW EXECUTE FUNCTION fabric.reject_history_change();
CREATE TRIGGER immutable_receipt BEFORE UPDATE OR DELETE ON fabric.approval_receipts FOR EACH ROW EXECUTE FUNCTION fabric.reject_history_change();
CREATE TRIGGER immutable_approval_outbox BEFORE UPDATE OR DELETE ON fabric.approval_outbox FOR EACH ROW EXECUTE FUNCTION fabric.reject_history_change();
CREATE FUNCTION fabric.protect_exact_approval() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,fabric AS $$ BEGIN IF TG_OP='DELETE' OR ROW(NEW.tenant_id,NEW.space_id,NEW.approval_id,NEW.requester_id,NEW.executor_id,NEW.request_identity,NEW.binding,NEW.binding_digest) IS DISTINCT FROM ROW(OLD.tenant_id,OLD.space_id,OLD.approval_id,OLD.requester_id,OLD.executor_id,OLD.request_identity,OLD.binding,OLD.binding_digest) OR(OLD.approver_id IS NOT NULL AND ROW(NEW.approver_id,NEW.approver_identity) IS DISTINCT FROM ROW(OLD.approver_id,OLD.approver_identity)) OR(OLD.state='consumed' AND NEW.state<>'consumed') OR(OLD.state='approved' AND NEW.state='pending') THEN RAISE EXCEPTION 'immutable approval binding';END IF;RETURN NEW;END $$;
CREATE TRIGGER immutable_exact_binding BEFORE UPDATE OR DELETE ON fabric.exact_approvals FOR EACH ROW EXECUTE FUNCTION fabric.protect_exact_approval();
DO $$ DECLARE n text;BEGIN FOREACH n IN ARRAY ARRAY['identity_target_versions','exact_approvals','approval_receipts','approval_audit','approval_outbox'] LOOP EXECUTE format('ALTER TABLE fabric.%I ENABLE ROW LEVEL SECURITY',n);EXECUTE format('ALTER TABLE fabric.%I FORCE ROW LEVEL SECURITY',n);EXECUTE format('CREATE POLICY identity_scope ON fabric.%I USING(fabric.service_scope(tenant_id,space_id)) WITH CHECK(fabric.service_scope(tenant_id,space_id))',n);END LOOP;END $$;
CREATE FUNCTION fabric.identity_authority(i text,u text,sid_value text,t uuid,sp uuid) RETURNS jsonb LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,fabric AS $$ SELECT jsonb_build_object('tenantId',s.tenant_id,'spaceId',s.space_id,'actorId',a.actor_id,'payerId',s.payer_actor_id,'authorityRevision',s.authority_revision,'membershipRevision',m.revision,'grants',m.grants,'actorRevoked',a.revoked_at IS NOT NULL OR id.revoked_at IS NOT NULL,'payerRevoked',p.revoked_at IS NOT NULL,'membershipRevoked',m.revoked_at IS NOT NULL,'lifecycle',s.lifecycle,'principalKind',id.principal_kind,'sessionExpiresAt',ss.expires_at) FROM fabric.identities id JOIN fabric.identity_sessions ss USING(issuer,subject) JOIN fabric.actors a ON a.tenant_id=id.tenant_id AND a.actor_id=id.actor_id JOIN fabric.spaces s ON s.tenant_id=id.tenant_id JOIN fabric.actors p ON p.tenant_id=s.tenant_id AND p.actor_id=s.payer_actor_id JOIN fabric.memberships m ON m.tenant_id=s.tenant_id AND m.space_id=s.space_id AND m.actor_id=a.actor_id WHERE id.issuer=i AND id.subject=u AND ss.sid=sid_value AND ss.revoked_at IS NULL AND ss.expires_at>clock_timestamp() AND s.tenant_id=t AND s.space_id=sp $$;
CREATE FUNCTION fabric.identity_lock_session(i text,u text,sid_value text) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,fabric AS $$ DECLARE id fabric.identities%ROWTYPE;ss fabric.identity_sessions%ROWTYPE;BEGIN IF current_setting('app.identity_verified',true) IS DISTINCT FROM 'true' THEN RETURN false;END IF;SELECT * INTO id FROM fabric.identities WHERE issuer=i AND subject=u FOR SHARE;IF NOT FOUND OR id.revoked_at IS NOT NULL OR id.tenant_id<>fabric.current_tenant() OR id.actor_id<>fabric.current_identity() THEN RETURN false;END IF;SELECT * INTO ss FROM fabric.identity_sessions WHERE issuer=i AND subject=u AND sid=sid_value FOR SHARE;RETURN FOUND AND ss.revoked_at IS NULL AND ss.expires_at>clock_timestamp();END $$;
CREATE FUNCTION fabric.identity_issue_session(i text,u text,sid_value text,expires timestamptz) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,fabric AS $$ BEGIN PERFORM 1 FROM fabric.identities WHERE issuer=i AND subject=u AND revoked_at IS NULL FOR SHARE;IF NOT FOUND OR expires<=clock_timestamp() OR expires>clock_timestamp()+interval '1 hour' OR length(sid_value)>256 THEN RAISE EXCEPTION 'identity session denied';END IF;INSERT INTO fabric.identity_sessions(issuer,subject,sid,expires_at) VALUES(i,u,sid_value,expires);END $$;
CREATE FUNCTION fabric.identity_revoke_session(i text,u text,sid_value text) RETURNS void LANGUAGE sql SECURITY DEFINER SET search_path=pg_catalog,fabric AS $$ UPDATE fabric.identity_sessions SET revoked_at=clock_timestamp() WHERE issuer=i AND subject=u AND sid=sid_value $$;
CREATE FUNCTION fabric.identity_party(actor uuid,needed text,identity jsonb,require_human boolean) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,fabric AS $$ DECLARE m fabric.memberships%ROWTYPE;id fabric.identities%ROWTYPE;ss fabric.identity_sessions%ROWTYPE;BEGIN PERFORM 1 FROM fabric.actors WHERE tenant_id=fabric.current_tenant() AND actor_id=actor AND revoked_at IS NULL FOR SHARE;IF NOT FOUND THEN RETURN false;END IF;SELECT * INTO m FROM fabric.memberships WHERE tenant_id=fabric.current_tenant() AND space_id=fabric.current_space() AND actor_id=actor FOR SHARE;IF NOT FOUND OR m.revoked_at IS NOT NULL OR NOT(m.grants ? needed) THEN RETURN false;END IF;SELECT * INTO id FROM fabric.identities WHERE issuer=identity->>'issuer' AND subject=identity->>'subject' AND tenant_id=fabric.current_tenant() AND actor_id=actor FOR SHARE;IF NOT FOUND OR id.revoked_at IS NOT NULL OR(require_human AND id.principal_kind<>'human') THEN RETURN false;END IF;SELECT * INTO ss FROM fabric.identity_sessions WHERE issuer=id.issuer AND subject=id.subject AND sid=identity->>'sessionId' FOR SHARE;RETURN FOUND AND ss.revoked_at IS NULL AND ss.expires_at>clock_timestamp();END $$;
-- Acquire every party lock first: an earlier session can expire while a later
-- lock waits. Recheck all participants against one fresh database timestamp.
CREATE FUNCTION fabric.identity_parties_current(parties jsonb) RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,fabric AS $$
DECLARE party jsonb; checked_at timestamptz;
BEGIN
 IF current_setting('app.identity_verified',true) IS DISTINCT FROM 'true' OR fabric.current_tenant() IS NULL OR fabric.current_identity() IS NULL OR jsonb_typeof(parties) IS DISTINCT FROM 'array' THEN RETURN false;END IF;
 IF jsonb_array_length(parties)<1 OR jsonb_array_length(parties)>3 THEN RETURN false;END IF;
 FOR party IN SELECT value FROM jsonb_array_elements(parties) LOOP
  IF fabric.identity_party((party->>'actorId')::uuid,party->>'grant',party->'identity',(party->>'human')::boolean) IS DISTINCT FROM true THEN RETURN false;END IF;
 END LOOP;
 checked_at:=clock_timestamp();
 FOR party IN SELECT value FROM jsonb_array_elements(parties) LOOP
  IF NOT EXISTS(
   SELECT 1 FROM fabric.actors a
   JOIN fabric.memberships m ON m.tenant_id=a.tenant_id AND m.actor_id=a.actor_id AND m.space_id=fabric.current_space()
   JOIN fabric.identities id ON id.tenant_id=a.tenant_id AND id.actor_id=a.actor_id
   JOIN fabric.identity_sessions ss ON ss.issuer=id.issuer AND ss.subject=id.subject
   WHERE a.tenant_id=fabric.current_tenant() AND a.actor_id=(party->>'actorId')::uuid
    AND a.revoked_at IS NULL AND m.revoked_at IS NULL AND m.grants ? (party->>'grant')
    AND id.issuer=party->'identity'->>'issuer' AND id.subject=party->'identity'->>'subject' AND id.revoked_at IS NULL
    AND (NOT (party->>'human')::boolean OR id.principal_kind='human')
    AND ss.sid=party->'identity'->>'sessionId' AND ss.revoked_at IS NULL AND ss.expires_at>checked_at
    AND jsonb_typeof(party->'identity'->'tokenExpiresAt')='number'
    AND (party->'identity'->>'tokenExpiresAt')::numeric>EXTRACT(EPOCH FROM checked_at)
    AND (party->'identity'->>'tokenExpiresAt')::numeric<'Infinity'::numeric
  ) THEN RETURN false;END IF;
 END LOOP;
 RETURN true;
END $$;
-- Both source and destination authority stay locked until the caller's transaction
-- commits. Payers need not be audience members, so membership actor locks alone
-- cannot prevent their revocation racing a disclosure or approval consumption.
CREATE FUNCTION fabric.identity_audience(source uuid,dest uuid,task uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,fabric AS $$
DECLARE result jsonb; source_space fabric.spaces%ROWTYPE; dest_space fabric.spaces%ROWTYPE; t uuid:=fabric.current_tenant();
BEGIN
 IF current_setting('app.identity_verified',true) IS DISTINCT FROM 'true' OR t IS NULL OR fabric.current_identity() IS NULL OR dest IS DISTINCT FROM fabric.current_space() THEN RETURN NULL;END IF;
 LOCK TABLE fabric.memberships IN SHARE MODE;
 PERFORM 1 FROM fabric.spaces WHERE tenant_id=t AND space_id IN(source,dest) ORDER BY space_id FOR SHARE;
 SELECT * INTO source_space FROM fabric.spaces WHERE tenant_id=t AND space_id=source;
 IF NOT FOUND OR source_space.lifecycle<>'active' THEN RETURN NULL;END IF;
 SELECT * INTO dest_space FROM fabric.spaces WHERE tenant_id=t AND space_id=dest;
 IF NOT FOUND OR dest_space.lifecycle<>'active' THEN RETURN NULL;END IF;
 IF NOT EXISTS(SELECT 1 FROM fabric.tasks WHERE tenant_id=t AND space_id=source AND task_id=task) THEN RETURN NULL;END IF;
 -- Lock the union in actor order, including payer actors absent from memberships.
 PERFORM 1 FROM fabric.actors WHERE tenant_id=t AND (actor_id IN(source_space.payer_actor_id,dest_space.payer_actor_id) OR actor_id IN(SELECT actor_id FROM fabric.memberships WHERE tenant_id=t AND space_id IN(source,dest))) ORDER BY actor_id FOR SHARE;
 IF NOT EXISTS(SELECT 1 FROM fabric.actors WHERE tenant_id=t AND actor_id=source_space.payer_actor_id AND revoked_at IS NULL) OR NOT EXISTS(SELECT 1 FROM fabric.actors WHERE tenant_id=t AND actor_id=dest_space.payer_actor_id AND revoked_at IS NULL) THEN RETURN NULL;END IF;
 SELECT jsonb_agg(jsonb_build_object('actorId',d.actor_id,'destinationRevision',d.revision,'sourceRevision',s.revision,'sourceRevoked',s.revoked_at IS NOT NULL,'sourceGrants',s.grants,'actorRevoked',a.revoked_at IS NOT NULL,'sourcePayerId',source_space.payer_actor_id,'sourceAuthorityRevision',source_space.authority_revision,'destinationPayerId',dest_space.payer_actor_id,'destinationAuthorityRevision',dest_space.authority_revision) ORDER BY d.actor_id) INTO result FROM fabric.memberships d JOIN fabric.actors a ON a.tenant_id=d.tenant_id AND a.actor_id=d.actor_id LEFT JOIN fabric.memberships s ON s.tenant_id=d.tenant_id AND s.space_id=source AND s.actor_id=d.actor_id WHERE d.tenant_id=t AND d.space_id=dest AND d.revoked_at IS NULL;
 RETURN coalesce(result,'[]'::jsonb);
END $$;
CREATE FUNCTION fabric.identity_target_current(target_value text,task_value uuid,run_value uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,fabric AS $$ DECLARE result jsonb;BEGIN PERFORM 1 FROM fabric.tasks WHERE tenant_id=fabric.current_tenant() AND space_id=fabric.current_space() AND task_id=task_value FOR SHARE;PERFORM 1 FROM fabric.runs WHERE tenant_id=fabric.current_tenant() AND space_id=fabric.current_space() AND run_id=run_value FOR SHARE;PERFORM 1 FROM fabric.identity_target_versions WHERE tenant_id=fabric.current_tenant() AND space_id=fabric.current_space() AND target=target_value FOR SHARE;SELECT jsonb_build_object('requirementsRevision',t.revision,'runRequirementsRevision',r.requirement_revision,'policyRevision',s.authority_revision,'artifactVersion',v.artifact_version,'argsDigest',v.args_digest) INTO result FROM fabric.tasks t JOIN fabric.runs r ON r.tenant_id=t.tenant_id AND r.space_id=t.space_id AND r.task_id=t.task_id JOIN fabric.spaces s ON s.tenant_id=t.tenant_id AND s.space_id=t.space_id JOIN fabric.identity_target_versions v ON v.tenant_id=t.tenant_id AND v.space_id=t.space_id WHERE t.tenant_id=fabric.current_tenant() AND t.space_id=fabric.current_space() AND t.task_id=task_value AND r.run_id=run_value AND v.target=target_value;RETURN result;END $$;
REVOKE ALL ON fabric.identities,fabric.identity_sessions,fabric.identity_target_versions,fabric.exact_approvals,fabric.approval_receipts,fabric.approval_audit,fabric.approval_outbox FROM PUBLIC,fabric_worker,fabric_test_idp;
GRANT USAGE ON SCHEMA fabric TO fabric_test_idp;
GRANT SELECT,INSERT,UPDATE ON fabric.exact_approvals TO fabric_controller;
GRANT SELECT,INSERT ON fabric.approval_receipts,fabric.approval_audit,fabric.approval_outbox TO fabric_controller;
REVOKE ALL ON FUNCTION fabric.identity_authority(text,text,text,uuid,uuid),fabric.identity_lock_session(text,text,text),fabric.identity_issue_session(text,text,text,timestamptz),fabric.identity_revoke_session(text,text,text),fabric.identity_party(uuid,text,jsonb,boolean),fabric.identity_parties_current(jsonb),fabric.identity_audience(uuid,uuid,uuid),fabric.identity_target_current(text,uuid,uuid),fabric.protect_exact_approval() FROM PUBLIC,fabric_worker,fabric_controller,fabric_test_idp;
GRANT EXECUTE ON FUNCTION fabric.identity_authority(text,text,text,uuid,uuid),fabric.identity_lock_session(text,text,text),fabric.identity_party(uuid,text,jsonb,boolean),fabric.identity_parties_current(jsonb),fabric.identity_audience(uuid,uuid,uuid),fabric.identity_target_current(text,uuid,uuid) TO fabric_controller;
GRANT EXECUTE ON FUNCTION fabric.identity_issue_session(text,text,text,timestamptz),fabric.identity_revoke_session(text,text,text) TO fabric_test_idp;
COMMIT;
